//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TecnoCutPlateChanger.rc
//
#define IDS_PROJNAME                    100
#define IDR_PLATECHANGER                102
#define IDD_MONITOR                     201
#define IDC_M_XPOS                      201
#define IDC_M_THPOS                     201
#define IDC_M_YPOS                      202
#define IDI_ICON64                      202
#define IDC_M_ZPOS                      203
#define IDI_ICON32                      203
#define IDC_M_XRED                      204
#define IDD_EDIT_CONFIG                 204
#define IDD_EDIT_PLATECHANGER_CONFIG    204
#define IDC_M_THRED                     204
#define IDC_M_XGREEN                    205
#define IDC_M_THGREEN                   205
#define IDC_M_YRED                      206
#define IDC_M_RDYRED                    206
#define IDC_M_YGREEN                    207
#define IDC_M_RDYGREEN                  207
#define IDC_M_ZRED                      208
#define IDC_M_RDYRED2                   208
#define IDC_M_ZGREEN                    209
#define IDC_M_RDYGREEN2                 209
#define IDC_M_HIDE                      210
#define IDC_M_TOGGLEMANUAL              211
#define IDC_M_RESET                     212
#define IDC_M_XYSPEED                   213
#define IDC_M_ZSPEED                    214
#define IDC_M_LIGHT                     215
#define IDC_M_LIGHTLEVEL                216
#define IDC_M_10                        217
#define IDC_EC_BOARDID                  217
#define IDC_M_1                         218
#define IDC_EC_ACCELFACT                218
#define IDC_EC_INVLIMPOL                219
#define IDC_M_100                       219
#define IDC_EC_CONSTSPEEDACCEL          220
#define IDC_EC_XY_ACCEL                 221
#define IDC_EC_XY_ENC2MICRON            222
#define IDC_EC_XY_LINESREV              223
#define IDC_EC_XY_STEPSREV              224
#define IDC_EC_XY_MANMAXSPEED           225
#define IDC_EC_XY_MANSPEEDMULT          226
#define IDC_EC_XY_MAXSPEED              227
#define IDC_EC_XY_MANMAXSPEEDCHANGE     228
#define IDC_EC_Z_ENC2MICRON             229
#define IDC_EC_Z_STEPSREV               230
#define IDC_EC_Z_LINESREV               231
#define IDC_EC_Z_ACCEL                  232
#define IDC_EC_Z_MAXSPEED               233
#define IDC_EC_Z_MANSPEEDMULT           234
#define IDC_EC_Z_MANMAXSPEED            235
#define IDC_EC_Z_MANMAXSPEEDCHANGE      236
#define IDC_EC_STEPDIR                  237
#define IDC_EC_CWCCW                    238
#define IDC_EC_LIGHTLIMIT               239
#define IDC_EC_INVERTX                  240
#define IDC_EC_INVERTY                  241
#define IDC_EC_POS_WAIT                 241
#define IDC_EC_POS_WAIT_TH              241
#define IDC_EC_INVERTZ                  242
#define IDC_EC_POS_PICKUP               242
#define IDC_EC_POS_PICKUP_TH            242
#define IDC_BUTTON_GO_X                 242
#define IDC_EC_POS_RELEASE              243
#define IDC_EC_POS_RELEASE_TH           243
#define IDC_CHECK_IN1_X                 243
#define IDC_EC_POS_SCANNINGSTAGE        244
#define IDC_EC_POS_SCANNINGSTAGE_TH     244
#define IDC_CHECK_IN0_X                 244
#define IDC_EC_SPEED_WAIT               245
#define IDC_EC_SPEED_WAIT_TH            245
#define IDC_CHECK_IN2_X                 245
#define IDC_EC_ACC_WAIT                 246
#define IDC_EC_ACC_WAIT_TH              246
#define IDC_CHECK_IN3_X                 246
#define IDC_EC_SPEED_PICKUP             247
#define IDC_EC_SPEED_PICKUP_TH          247
#define IDC_CHECK_IN4_X                 247
#define IDC_EC_ACC_PICKUP               248
#define IDC_EC_ACC_PICKUP_TH            248
#define IDC_CHECK_IN5_X                 248
#define IDC_EC_SPEED_RELEASE            249
#define IDC_EC_SPEED_RELEASE_TH         249
#define IDC_CHECK_IN6_X                 249
#define IDC_EC_ACC_RELEASE              250
#define IDC_EC_ACC_RELEASE_TH           250
#define IDC_CHECK_IN7_X                 250
#define IDC_EC_SPEED_SCAN               251
#define IDC_EC_SPEED_SCAN_TH            251
#define IDC_BUTTON_READ                 251
#define IDC_EC_ACC_SCAN                 252
#define IDC_EC_ACC_SCAN_TH              252
#define IDC_STATIC_PORT1                252
#define IDC_EC_SPEED_SAFE               253
#define IDC_EC_SPEED_SAFE_TH            253
#define IDC_STATIC_SET_X                253
#define IDC_EC_ACC_SAFE                 254
#define IDC_EC_ACC_SAFE_TH              254
#define IDC_STATIC_SET_Z                254
#define IDC_EC_POS_WAIT_Z               255
#define IDC_CHECK_IN1_Z                 255
#define IDC_EC_POS_SAFE                 256
#define IDC_EC_POS_SAFE_TH              256
#define IDC_CHECK_IN0_Z                 256
#define IDC_EC_POS_PICKUP_Z             257
#define IDC_CHECK_IN2_Z                 257
#define IDC_EC_POS_RELEASE_Z            258
#define IDC_CHECK_IN3_Z                 258
#define IDC_EC_POS_SCANNINGSTAGE_Z      259
#define IDC_CHECK_IN4_Z                 259
#define IDC_EC_POS_SAFE_Z               260
#define IDC_CHECK_IN5_Z                 260
#define IDC_EC_SPEED_WAIT_Z             261
#define IDC_CHECK_IN6_Z                 261
#define IDC_EC_ACC_WAIT_Z               262
#define IDC_CHECK_IN7_Z                 262
#define IDC_EC_SPEED_PICKUP_Z           263
#define IDC_STATIC_PORT0                263
#define IDC_EC_ACC_PICKUP_Z             264
#define IDC_BUTTON_POW_X                264
#define IDC_EC_SPEED_RELEASE_Z          265
#define IDC_BUTTON_POW_Z                265
#define IDC_EC_ACC_RELEASE_Z            266
#define IDC_BUTTON_GO_Z                 266
#define IDC_EC_SPEED_SCAN_Z             267
#define IDC_EDIT_XPOSMSG                267
#define IDC_EC_ACC_SCAN_Z               268
#define IDC_EDIT_ZPOSMSG                268
#define IDC_EC_SPEED_SAFE_Z             269
#define IDC_STATIC_SOURCE               269
#define IDC_EC_ACC_SAFE_Z               270
#define IDC_STATIC_SCANNED              270
#define IDC_EC_COMPORT                  271
#define IDC_EDIT_SOURCE                 271
#define IDC_EDIT_SCANNED                272
#define IDC_STATIC_SOURCE2              273
#define IDC_BUTTON_CHANGE               274
#define IDC_STATIC_SCANNED2             275
#define IDC_INITIALIZE                  276
#define IDC_LOAD                        277
#define IDC_UNLOAD                      278
#define IDC_EDIT_SOURCE2                279
#define IDC_EDIT_SCANNED2               280
#define IDC_BUTTON_VACON                281
#define IDC_BUTTON_VACOFF               282
#define IDC_CHECK_SEPARATOR             283
#define IDC_STATIC_SCANNED3             284
#define IDC_MVSEP                       285
#define IDC_CHGPLT                      286
#define IDC_CHGPLT2                     287
#define IDC_BUTTON_VACON2               288
#define IDC_BUTTON_VACOFF2              289
#define IDC_SORT                        290
#define IDC_LOADBANK                    291
#define IDC_EDIT_SCANNED3               292
#define IDC_EDIT_SOURCE3                293
#define IDC_STATIC_SOURCE3              294
#define IDC_STATIC_SCANNED4             295
#define IDC_BANK0                       296
#define IDC_BANK1                       297
#define IDC_BANK2                       298
#define IDC_BANK3                       299
#define IDC_STATIC_EMINBRICK            300
#define IDC_EDIT_NUMEM                  301
#define IDC_STATIC_SCANNED6             302
#define IDC_CHECK_SEPARATOR2            303
#define IDC_STATIC_SCANNED5             304
#define IDC_EDIT_BRICK                  305
#define IDC_DEBUGLEVEL                  306
#define IDC_BANK4                       307
#define IDC_EDIT_PLID0                  308
#define IDC_EDIT_PLID1                  309
#define IDC_LOADEMID                    310
#define IDC_EDIT_PLID2                  311
#define IDC_EDIT_PLID3                  312
#define IDC_EDIT_PLID4                  313
#define IDC_EDIT_PLID5                  314
#define IDC_EDIT_PLID6                  315
#define IDC_EDIT_PLID7                  316
#define IDC_UNLOADEM                    317
#define IDC_WITHSEPARATORS              318
#define IDC_HOMESTAGE                   318
#define IDC_NUMBEROFATTEMPT             319
#define IDC_STATIC_SCANNED7             319
#define IDC_NUMBEROFBANKS               320
#define IDC_INITIALIZE2                 320
#define IDC_SEPATTEMPTS                 321
#define IDC_BUTTON_POWERON              321
#define IDC_VACTIMEOUT                  322
#define IDC_BUTTON_POWEROFF             322
#define IDC_AIRTIMEOUT                  323
#define IDC_POSTIMEOUT                  324
#define IDC_LIMOFFSETX                  325
#define IDC_LIMOFFSETY                  326
#define IDC_FMOFFSETY                   327
#define IDC_FMOFFSETX                   328
#define IDC_EDIT_STATUSBOX              328
#define IDC_FMOFFSETZ                   329
#define IDC_LIMOFFSETZ                  330
#define IDC_SPEEDX2                     331
#define IDC_SPEEDY2                     332
#define IDC_LIGHTLEVEL                  333
#define IDC_ACCX3                       334
#define IDC_ACCY3                       335
#define IDC_ACCZ3                       336
#define IDC_LIFTCORNERS                 337
#define IDC_COMPORT                     338
#define IDC_SPEEDZ2                     346
#define IDC_LABEL                       350
#define IDC_EC_CHANGEME                 351
#define IDC_EC_CHANGEME2                352

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         352
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
