//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Odyssey1.rc
//
#define IDC_EC_TEST                     3
#define IDC_TC_HELP                     3
#define IDC_GC_COMPUTE                  3
#define IDC_TQ_START                    3
#define IDC_EC_HELP                     4
#define IDS_PROJNAME                    100
#define IDR_ODYSSEY                     102
#define IDI_ICON64                      201
#define IDI_ICON32                      202
#define IDC_XOP_COPY_TITLE              202
#define IDD_EDIT_CONFIG                 203
#define IDC_XOP_COPY_LIST               203
#define IDC_XOP_LIST                    203
#define IDC_XOP_COPY_SRC                205
#define IDD_TEST_CONFIG                 205
#define IDC_XOP_COPY_SRC_L              206
#define IDC_XOP_SRC_L                   206
#define IDC_ODYSSEY                     206
#define IDC_XOP_COPY_SRC_T              207
#define IDC_XOP_SRC_T                   207
#define IDD_SEL_GRAB_BUFFER             207
#define IDC_XOP_COPY_SRC_W              208
#define IDC_XOP_SRC_W                   208
#define IDC_XOP_COPY_SRC_H              209
#define IDC_XOP_SRC_H                   209
#define IDD_MAKE_FILTER_EQ              209
#define IDC_XOP_COPY_DEST               210
#define IDB_THEME                       210
#define IDD_OPTIMIZE_PROGRAM            211
#define IDC_XOP_COPY_DEST_L             211
#define IDC_XOP_DEST_L                  211
#define IDC_XOP_COPY_DEST_T             212
#define IDC_XOP_DEST_T                  212
#define IDD_GAIN_COMPENSATION           212
#define IDC_XOP_COPY_DEST_W             213
#define IDC_XOP_DEST_W                  213
#define IDD_THRESHOLD_EQ_MAP            213
#define IDC_XOP_COPY_DEST_H             214
#define IDC_XOP_DEST_H                  214
#define IDC_XOP_COPY_ADD                215
#define IDC_XOP_ADD                     215
#define IDC_XOP_COPY_SET                216
#define IDC_XOP_SET                     216
#define IDC_XOP_COPY_COPY               217
#define IDC_XOP_COPY                    217
#define IDC_XOP_COPY_DEL                218
#define IDC_XOP_DEL                     218
#define IDC_PROGRAM_NEW                 220
#define IDC_PROGRAM_REMOVE              221
#define IDC_PROG_K00                    222
#define IDC_PROG_K01                    223
#define IDC_PROG_K02                    224
#define IDC_PROG_K03                    225
#define IDC_PROG_K10                    226
#define IDC_PROG_K11                    227
#define IDC_PROG_K12                    228
#define IDC_PROG_K13                    229
#define IDC_PROG_K20                    230
#define IDC_PROG_K21                    231
#define IDC_PROG_K22                    232
#define IDC_PROG_K23                    233
#define IDC_PROG_K30                    234
#define IDC_PROG_K31                    235
#define IDC_PROG_K32                    236
#define IDC_PROG_K33                    237
#define IDC_PROG_KWIDTH                 238
#define IDC_PROG_KHEIGHT                239
#define IDC_PROG_CUTOFF                 240
#define IDC_PROG_OFFX                   241
#define IDC_PROG_MAXPROCESSORS          242
#define IDC_PROG_SELFLATFIELD           242
#define IDC_PROG_OFFY                   243
#define IDC_PROG_TAB                    244
#define IDC_PROG_WINWIDTH               245
#define IDC_PROG_WINHEIGHT              246
#define IDC_TS_ACTIVEPROGRAM            246
#define IDC_TS_FINDCLUSTERS             247
#define IDC_PROG_ASTYGCOEFF             247
#define IDC_PROG_FLATFIELD              247
#define IDC_TS_DUMPCLUSTERS             248
#define IDC_PROG_XCENTER                248
#define IDC_PROG_SELFILTEREQ            248
#define IDC_TS_SELCLUSTERFILE           249
#define IDC_PROG_YCENTER                249
#define IDC_PROG_FILTEREQ               249
#define IDC_TS_CLUSTERFILE              250
#define IDC_TS_FOUND                    251
#define IDC_TS_DUMPIMAGE                252
#define IDC_TS_SELIMAGEFILE             253
#define IDC_TS_IMAGEFILE                254
#define IDC_TS_SHOWCLUSTERS             255
#define IDC_PROG_ASTYGMATISM            256
#define IDC_TS_GRAYLEVEL                256
#define IDC_TS_MAXCLUSTERS              257
#define IDC_TS_ASYNCFINDCLUSTERS        258
#define IDC_TS_IMAGES                   259
#define IDC_LC_MINLEV                   259
#define IDC_LC_MAXLEV                   260
#define IDC_TS_TESTAUTOLIGHT            260
#define IDC_TS_AVAILABLEPROCESSORS      261
#define IDC_EC_REFRESHCYCLETIME         261
#define IDC_LC_TIMECONST                262
#define IDC_TS_MAXASYNCFRAMES           262
#define IDC_LC_TARGETGRAYLEV            263
#define IDC_TS_INQUIRE                  263
#define IDC_LC_TARGETSATURATION         264
#define IDC_TS_CAMERAFRAMERATE          264
#define IDC_LC_SATGRAYLEV               265
#define IDC_TS_CHECKFRAMERATE           265
#define IDC_TS_COMMANDQUEUELENGTH       266
#define IDC_EC_CLUSTERINGPROCESSORS     266
#define IDC_TS_MAKEFLATFIELD            267
#define IDC_EC_PROCESSINGSTARTDELAY     267
#define IDC_XOP_TYPE                    268
#define IDC_TS_FLATFIELDIMGCOUNT        268
#define IDC_GB_BANK                     269
#define IDC_TS_MAKEFILTEREQ             269
#define IDC_GB_NUMBER                   270
#define IDC_FE_XCENTER                  270
#define IDC_TS_ASYNCOPTIMIZE            270
#define IDC_FE_YCENTER                  271
#define IDC_PO_MINCUTOFF                271
#define IDC_TS_GRABTIMEFRAME            271
#define IDC_GC_XWAVES                   271
#define IDC_TS_PROCESSTIMEFRAME         272
#define IDC_FE_COMPFACT                 272
#define IDC_PO_MAXCUTOFF                272
#define IDC_GC_YWAVES                   272
#define IDC_PO_CUTOFFSCANSTEP           273
#define IDC_GC_XSAMPLINGFACTOR          273
#define IDC_PO_SCANCUTOFF               274
#define IDC_GC_YSAMPLINGFACTOR          274
#define IDC_PO_DISPLAY                  275
#define IDC_GC_PANEL                    275
#define IDC_PO_MINCLUSTERSIZE           276
#define IDC_GC_MINMAXGAIN               276
#define IDC_TQ_WIDTH                    276
#define IDC_PO_MAXCLUSTERSIZE           277
#define IDC_GC_MINGREYLEVEL             277
#define IDC_TQ_HEIGHT                   277
#define IDC_PO_MAXCLUSTERS              278
#define IDC_TQ_XWAVES                   279
#define IDC_TQ_YWAVES                   280
#define IDC_TQ_XSAMPLINGFACTOR          281
#define IDC_TQ_YSAMPLINGFACTOR          282
#define IDC_TQ_MINAREA                  283
#define IDC_TQ_MINMULT                  284
#define IDC_TQ_MAXMULT                  285
#define IDC_TQ_MULTSTEPS                286
#define IDC_TQ_PANEL                    287
#define IDC_FQ_OPT                      288

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         289
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
