// Thin3DTracker.idl : IDL source for Thin3DTracker.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Thin3DTracker.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\Common\Connection.h";
import "..\Common\Config.h";
import "..\Common\GUIdefs.h";
import "..\Common\Cluster.h";
import "..\Common\CameraSpec.h";
import "..\Common\Track.h";
	[
		object,
		uuid(C022EEAD-748A-11D3-A47B-E89C0BCE9720),
	
		helpstring("ISySalObject Interface"),
		pointer_default(unique)
	]
	interface ISySalObject : IUnknown
	{
		[helpstring("method SetName")] HRESULT SetName(ConnectionName name);
		[helpstring("method GetName")] HRESULT GetName(ConnectionName name);
		[helpstring("method SetConfig")] HRESULT SetConfig(SySalConfig *pConfig);
		[helpstring("method GetConfig")] HRESULT GetConfig(SySalConfig *pConfig);
		[helpstring("method EditConfig")] HRESULT EditConfig(SySalConfig *pConfig, HSySalHANDLE hWnd);
		[helpstring("method EnableMonitor")] HRESULT EnableMonitor(boolean bEnable);
		[helpstring("method GetNumberOfConnections")] HRESULT GetNumberOfConnections(int *pNumber);
		[helpstring("method SetConnection")] HRESULT SetConnection(int n, SySalConnection connection);
		[helpstring("method GetConnection")] HRESULT GetConnection(int n, SySalConnection *pConnection);
		[helpstring("method GetIcon")] HRESULT GetIcon(int n, HSySalHICON *pHICON);
		[helpstring("method GetClassName")] HRESULT GetClassName(ConnectionName name);
		[helpstring("method SyncExec")] HRESULT SyncExec();
		[helpstring("method AsyncExec")] HRESULT AsyncExec(HSySalHANDLE HNotifyStatusChangeEvent);
		[helpstring("method AsyncCheckStatus")] HRESULT AsyncCheckStatus(long *pStatus);
		[helpstring("method AsyncWait")] HRESULT AsyncWait();
		[helpstring("method AsyncPause")] HRESULT AsyncPause();
		[helpstring("method AsyncStop")] HRESULT AsyncStop();
		[helpstring("method AsyncResume")] HRESULT AsyncResume();
		[helpstring("method IsReady")] HRESULT IsReady(long *pWrongConn, long *pRetCode);
	};
	[
		object,
		uuid(E416C46D-7F68-11D3-A47C-FA1E4AFA2721),
	
		helpstring("ITracker Interface"),
		pointer_default(unique)
	]
	interface ITracker : IUnknown
	{
		[helpstring("method StartFilling")] HRESULT StartFilling();
		[helpstring("method SetCameraSpec")] HRESULT SetCameraSpec(CameraSpec Spec);
		[helpstring("method GetCameraSpec")] HRESULT GetCameraSpec(CameraSpec *pSpec);
		[helpstring("method PutClusters")] HRESULT PutClusters(Cluster *pClusters, int CountOfClusters, float Z);
		[helpstring("method GetTracks")] HRESULT GetTracks(Track *pSpace, int *pMaxNumber, int StartLayer, int EndLayer);
		[helpstring("method GetClusters")] HRESULT GetClusters(int Layer, Cluster *pSpace, int *pMaxNumber, float *pZ);
		[helpstring("method PresetSlope")] HRESULT PresetSlope(float SX, float SY, float AccX, float AccY);
		[helpstring("method EnableSlopePresetting")] HRESULT EnableSlopePresetting(boolean SlPresEnable);
		[helpstring("method GetSlopePresetStatus")] HRESULT GetSlopePresetStatus(boolean *pSlPresEnable);
	};

[
	uuid(976b9330-745c-4315-9101-e3fef680add1),
	version(1.0),
	helpstring("Thin3DTracker 1.0 Type Library")
]
library THIN3DTRACKERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(27d4a7c9-05e8-4691-bb60-cbbc0c397dec),
		helpstring("Thin3DTracker Class")
	]
	coclass Thin3DTrk
	{
		[default] interface ISySalObject;
		interface ITracker;
	};
};
