//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VertigoScan5.rc
//
#define IDC_SF_APPLYN                   3
#define IDC_IM_SELPATH                  3
#define IDC_TC_EDITCONFIG               4
#define IDC_SF_APPLYPOS                 4
#define IDC_TC_SAVECONFIG               5
#define IDS_PROJNAME                    100
#define IDR_VERTIGOSCAN5                102
#define IDI_ICON32                      201
#define IDC_MS_TESTCONFIG               201
#define IDI_ICON64                      202
#define IDC_MS_SCAN                     202
#define IDC_EC_FPS                      202
#define IDD_MAINSWITCH                  203
#define IDC_EC_TOPCLCONTRAST            203
#define IDC_TC_START                    203
#define IDC_MS_INITMAP                  203
#define IDB_WELCOME                     204
#define IDC_EC_TOPCLTHRESHOLD           204
#define IDC_TC_STOP                     204
#define IDC_MS_MANUALCHECKS             204
#define IDC_EC_BOTTOMCLCONTRAST         205
#define IDD_EDIT_CONFIG                 205
#define IDC_TC_GOTOFIELD                205
#define IDC_MS_REMOTESCAN               205
#define IDC_EC_BOTTOMCLTHRESHOLD        206
#define IDD_TEST_CONFIG                 206
#define IDC_TC_REFRESH                  206
#define IDC_EC_LIGHTLEVEL               207
#define IDC_TC_SAVEDATA                 207
#define IDD_SELECT_FIELD                207
#define IDC_EC_VLAYERS                  208
#define IDC_TC_TESTPROGRESS             208
#define IDD_SELECT_CONFIG_NAME          208
#define IDC_EC_VSTEP                    209
#define IDC_TC_XFIELDS                  209
#define IDD_EDIT_GRIDOPTS               209
#define IDC_EC_TOPVSTEP                 209
#define IDC_EC_VSPEED                   210
#define IDC_TC_YFIELDS                  210
#define IDC_EC_VACC                     211
#define IDC_TC_TIMESTRUCT               211
#define IDC_TC_IMAGEQUALITY             211
#define IDC_EC_VTOL                     212
#define IDC_TC_TOPTKS                   212
#define IDC_TC_BOTTOMTKS                213
#define IDC_EC_XSTEP                    213
#define IDD_INITMAP                     213
#define IDC_EC_HSPEED                   214
#define IDC_TC_TOTALTIME                214
#define IDD_SCAN                        214
#define IDC_EC_HACC                     215
#define IDC_TC_CYCLETIME                215
#define IDD_SCAN_START                  215
#define IDC_EC_HTOL                     216
#define IDC_TC_DUMPCLUSTERCOUNT         216
#define IDC_TC_DUMPGRABSTRUCT           216
#define IDD_MANUAL_CHECKS               216
#define IDC_EC_VMINLAYERS               217
#define IDC_TC_OBJLIST                  217
#define IDD_REMOTESCAN                  217
#define IDC_EC_VBASESPEED               218
#define IDC_TC_TOPAVGCLUSTERS           218
#define IDC_SF_FIELD                    218
#define IDC_EC_BASETHICKNESS            219
#define IDC_TC_BOTTOMAVGCLUSTERS        219
#define IDC_SF_XFIELD                   219
#define IDC_EC_FOCUSTOLERANCE           220
#define IDC_TC_DUMPTIMESTRUCT           220
#define IDC_SF_YFIELD                   220
#define IDC_EC_STAGEDELAY               221
#define IDC_TC_SHOWSTAGEMON             221
#define IDC_SF_DISPLAY                  221
#define IDC_EC_ZSCANDURATION            221
#define IDC_EC_MAXTRACKS                222
#define IDC_TC_SCANSPEED                222
#define IDC_SF_HIDE                     222
#define IDC_EC_YSTEP                    223
#define IDC_TC_SAVE                     223
#define IDC_EC_MAXCLUSTERS              224
#define IDC_TC_GRIDOPTIONS              224
#define IDC_EC_LIMITERDELAY             225
#define IDC_TC_DUMPFOCUSDATA            225
#define IDC_EC_SHRINKAGE                226
#define IDC_EC_XFIELDS                  227
#define IDC_EC_YFIELDS                  228
#define IDC_EC_LOCKONBASE               229
#define IDC_EC_LOCKONCENTER             230
#define IDC_SN_NAME                     230
#define IDC_EC_LOCKONCENTERVALLEY       231
#define IDC_TC_AUTOSAVE                 231
#define IDC_TC_TOGGLEGRID               232
#define IDC_EC_SCANTOP                  232
#define IDC_TC_FIELDN                   233
#define IDC_EC_SCANBOTTOM               233
#define IDC_EG_XSTEP                    234
#define IDC_EC_SCANBOTHTWOSIDES         234
#define IDC_TC_ENABLEREMOTECONTROL      234
#define IDC_TC_TS_GRAB                  235
#define IDC_EC_SCANBOTHINFIELD          235
#define IDC_EG_YSTEP                    236
#define IDC_TC_TT_GRAB                  236
#define IDC_EC_ZSAMPLEINTERVAL          236
#define IDC_TC_TS_PROC                  237
#define IDC_EC_FOCUSCLUSTERCONTRAST     237
#define IDC_EC_SURFACEADJUSTMENT        237
#define IDC_TC_TS_TRACK                 238
#define IDC_EC_XYZMOTIONDURATION        238
#define IDC_TC_TS_FIT                   239
#define IDC_EC_FOCUSZSAMPLEINTERVAL     239
#define IDC_TC_TS_XY                    240
#define IDC_IM_INITSTRING               240
#define IDC_EC_VINACTIVELAYERS          240
#define IDC_TC_TS_Z                     241
#define IDC_SM_ID1                      241
#define IDC_EC_TOPEXPCLUSTERS           241
#define IDC_SM_FRAGPROGRESS             242
#define IDC_EC_TOPCLUSTERSFLUCT         242
#define IDC_TC_TT_PROC                  243
#define IDC_SM_ID2                      243
#define IDC_EC_BOTTOMEXPCLUSTERS        243
#define IDC_TC_TT_TRACK                 244
#define IDC_SM_ID3                      244
#define IDC_EC_BOTTOMCLUSTERSFLUCT      244
#define IDC_TC_TT_FIT                   245
#define IDC_SM_ID4                      245
#define IDC_EC_TOPCLUSTERSMINAREA       245
#define IDC_TC_TT_XY                    246
#define IDC_EC_BOTTOMCLUSTERSMINAREA    246
#define IDC_EC_THICKNESSTOLERANCE       247
#define IDC_TC_TT_Z                     247
#define IDC_SM_TOTALFRAGMENTS           247
#define IDC_SM_CURRENTFRAGMENTS         248
#define IDC_SM_CURRENTFRAGMENT          248
#define IDC_EC_BOTTOMVSTEP              248
#define IDC_SM_TOTALVIEWS               249
#define IDC_SM_CURRENTVIEW              250
#define IDC_SM_VIEWPROGRESS             251
#define IDC_SM_TOTALTIME                252
#define IDC_SM_TIMETOCOMPL              253
#define IDC_SM_START                    254
#define IDC_SM_PAUSE                    255
#define IDC_SM_STOP                     256
#define IDC_SM_SETFOCUS                 257
#define IDC_SM_TOPTHICKNESS             257
#define IDC_SM_CONTINUE                 258
#define IDC_SM_CNTRS_TOPVALIDLAYERS     259
#define IDC_SM_BOTTOMTHICKNESS          259
#define IDC_SM_CNTRS_BOTTOMVALIDLAYERS  260
#define IDC_SS_ID1                      260
#define IDC_SM_CNTRS_TOPTRACKDENSITY    261
#define IDC_SS_ID2                      261
#define IDC_SM_CNTRS_BOTTOMTRACKDENSITY 262
#define IDC_SS_ID3                      262
#define IDC_SM_CNTRS_TOPAVGGRAINS       263
#define IDC_SS_ID4                      263
#define IDC_SM_CNTRS_BOTTOMAVGGRAINS    264
#define IDC_SS_MINX                     264
#define IDC_EC_PICTURE                  264
#define IDC_SM_CNTRS_FOCUSFAULTS        265
#define IDC_MS_PICTURE                  265
#define IDC_SS_SLOPEX                   265
#define IDC_SM_CNTRS_STAGEFAULTS        266
#define IDC_SS_MAXX                     266
#define IDC_SM_CNTRS_TOPIMAGEHOM        267
#define IDC_SS_SLOPEACCX                267
#define IDC_SS_MINY                     268
#define IDC_SM_CNTRS_BOTTOMIMAGEHOM     269
#define IDC_SS_MAXY                     269
#define IDC_SM_EXIT                     270
#define IDC_SS_STATIC_BATCHID           270
#define IDC_SS_STATIC_MINX              271
#define IDC_SS_STATIC_MAXX              272
#define IDC_SS_STATIC_MINY              273
#define IDC_SS_STATIC_MAXY              274
#define IDC_SS_SELCATALOG               275
#define IDC_SS_CATALOG                  276
#define IDC_SS_RESTORECONFIGS           277
#define IDC_SS_TAB                      278
#define IDC_MC_IX                       279
#define IDC_SS_STATIC_SLOPEX            279
#define IDC_MC_IY                       280
#define IDC_SS_STATIC_SLOPEACCX         280
#define IDC_MC_IZ                       281
#define IDC_SS_STATIC_SLOPEY            281
#define IDC_MC_SX                       282
#define IDC_SS_SLOPEY                   282
#define IDC_MC_SY                       283
#define IDC_SS_STATIC_SLOPEACCY         283
#define IDC_MC_SHOW                     284
#define IDC_SS_SLOPEACCY                284
#define IDC_MC_PX                       285
#define IDC_MC_ACTIVATEMOUSE            286
#define IDC_MC_GO                       287
#define IDC_TC_DUMPALLGRAINSTOASCII     288
#define IDC_MC_LOAD                     288
#define IDC_TC_GRAINFILE                289
#define IDC_MC_SELCHECKFILE             289
#define IDC_MC_SAVE                     290
#define IDC_TC_SAVEIMAGES               290
#define IDC_MC_CHECKFILE                291
#define IDC_TC_IMAGESEQ                 291
#define IDC_MS_CHECKLIST                292
#define IDC_MC_FLAGSEL                  293
#define IDC_MC_GOSEL                    294
#define IDC_MS_FLAGCODE                 295
#define IDC_MC_PY                       296
#define IDC_EC_COMPUTEZSAMPLES          296
#define IDC_MC_PZ                       297
#define IDC_MC_MYSX                     298
#define IDC_EC_TEST_SCANZSAMPLES        298
#define IDC_MC_MYSY                     299
#define IDC_EC_TEST_FOCUSZSAMPLES       299
#define IDC_SM_VALIDLAYERS              299
#define IDC_EC_TEST_MAXZSAMPLES         300
#define IDC_SM_TOPTRACKS                300
#define IDC_CHECK1                      300
#define IDC_SF_SHOWEXTRAPOLATION        300
#define IDC_SS_ENABLESLOPEPRESET        300
#define IDC_MC_FPX                      301
#define IDC_SM_BOTTOMTRACKS             301
#define IDC_MC_FPY                      302
#define IDC_MC_FPZ                      303
#define IDC_MC_SPX                      304
#define IDC_MC_SPY                      305
#define IDC_MC_SPZ                      306

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         301
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
