//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VideoImageScanner.rc
//
#define IDC_BP_START                    3
#define IDC_BP_STOP                     4
#define IDC_BP_CLEARLOG                 5
#define IDS_PROJNAME                    100
#define IDR_VIDIMGSCANNER               102
#define IDI_ICON64                      201
#define IDC_MS_CLUSTERANALYSIS          201
#define IDI_ICON32                      202
#define IDC_MS_INTERACTIVETRACKING      202
#define IDC_CA_LOADIMAGE                202
#define IDD_MAINSWITCH                  203
#define IDC_MS_BATCHPROCESSING          203
#define IDC_CA_SAVEIMAGE                203
#define IDC_MS_EXIT                     204
#define IDD_ABOUT                       204
#define IDC_CA_WHITECOLOR               204
#define IDC_MS_ABOUT                    205
#define IDD_CLUSTER_ANALYSIS            205
#define IDC_CA_THRESHOLD                205
#define IDC_MS_HELP                     206
#define IDC_CA_GRAYSCALE                206
#define IDD_RAW_SPECIFICATIONS          206
#define IDC_CA_INVGRAYSCALE             207
#define IDD_SELECT_PHS_IMAGE            207
#define IDC_CA_CUSTOMCOLORS             208
#define IDD_INTERACTIVE_TRACKING        208
#define IDC_CA_TOGGLEEQ                 209
#define IDD_SELNAME                     209
#define IDC_CA_BLACKCOLOR               210
#define IDC_RS_WIDTH                    210
#define IDD_SELOBJECT                   210
#define IDC_RS_HEIGHT                   211
#define IDC_CA_ZOOM                     211
#define IDD_BATCH_PROCESSING            211
#define IDC_CA_DUMPCLUSTERS             212
#define IDD_EDIT_CONFIG                 212
#define IDC_CA_BLACKWHITE               213
#define IDC_CA_WHITEBLACK               214
#define IDC_CA_DUMPHISTOGRAM            215
#define IDC_CA_ITERATIONS               216
#define IDC_CA_FINDCLUSTERS             217
#define IDC_CA_SHOWCLUSTERS             218
#define IDC_CA_AVGTIME                  219
#define IDC_CA_MINSIZE                  220
#define IDC_CA_MAXSIZE                  221
#define IDC_CA_TOTAL                    222
#define IDC_CA_INRANGE                  223
#define IDC_CA_ZOOMIN                   224
#define IDC_CA_ZOOMOUT                  225
#define IDC_CA_LOADIMAGEIO              226
#define IDC_SP_TOTAL                    228
#define IDC_SP_IMAGE                    229
#define IDC_SP_IMAGESPIN                230
#define IDC_SP_PREVIEW                  231
#define IDC_IT_SCREEN                   232
#define IDC_IT_LOAD                     233
#define IDC_IT_SAVE                     234
#define IDC_IT_THRESHOLD                235
#define IDC_IT_THRESHOLD0               235
#define IDC_IT_RELTHRESHOLD             236
#define IDC_IT_EQUALIZATION             237
#define IDC_IT_LAYERS                   238
#define IDC_IT_LAYERS0                  238
#define IDC_IT_STARTLAYER               239
#define IDC_IT_STARTLAYER0              239
#define IDC_IT_ENDLAYER                 240
#define IDC_IT_ENDLAYER0                240
#define IDC_IT_ITERATIONS               241
#define IDC_IT_AVGTIME                  242
#define IDC_IT_TRACK                    243
#define IDC_IT_EDITCONFIG               244
#define IDC_IT_SAVECONFIG               245
#define IDC_IT_MAXGRAINS                246
#define IDC_IT_MAXTRACKS                247
#define IDC_IT_CLUSTERPROGRESS          248
#define IDC_NAME                        249
#define IDC_IT_SHRINKAGE                249
#define IDC_SLOTLIST                    250
#define IDC_IT_THRESHOLD1               250
#define IDC_IT_LAYERS1                  251
#define IDC_IT_STARTLAYER1              252
#define IDC_IT_ENDLAYER1                253
#define IDC_BP_SAVECONFIG               254
#define IDC_BP_SHRINKAGE                255
#define IDC_BP_THRESHOLD0               256
#define IDC_BP_THRESHOLD1               257
#define IDC_BP_RELTHRESHOLD             258
#define IDC_BP_EQUALIZATION             259
#define IDC_BP_MAXGRAINS                260
#define IDC_BP_STARTLAYER0              263
#define IDC_BP_STARTLAYER1              264
#define IDC_BP_ENDLAYER0                265
#define IDC_BP_ENDLAYER1                266
#define IDC_BP_MAXTRACKS                267
#define IDC_BP_LOADCONFIG               268
#define IDC_BP_EDITCONFIG               268
#define IDC_BP_DIRECT                   270
#define IDC_BP_LISTFILE                 271
#define IDC_BP_PREDFILE                 272
#define IDC_BP_SELFILES                 273
#define IDC_BP_ESELFILE                 274
#define IDC_BP_STATUS                   275
#define IDC_BP_PERCENT                  276
#define IDC_BP_PROGRESS                 277
#define IDC_BP_TOPTKS                   278
#define IDC_BP_ELAPSEDTIME              279
#define IDC_BP_BOTTKS                   280
#define IDC_BP_TIMETOCOMPLETION         281
#define IDC_BP_ERRORCOUNT               282
#define IDC_BP_MSGLOG                   283
#define IDC_EC_SHRINKAGE                284
#define IDC_EC_THRESHOLD1               285
#define IDC_EC_THRESHOLD0               286
#define IDC_EC_RELTHRESHOLD             287
#define IDC_EC_EQUALIZATION             288
#define IDC_EC_MAXGRAINS                289
#define IDC_EC_STARTLAYER0              290
#define IDC_EC_STARTLAYER1              291
#define IDC_EC_ENDLAYER0                292
#define IDC_EC_ENDLAYER1                293
#define IDC_EC_MAXTRACKS                294
#define IDC_IT_MAXFLATTRACKS            295
#define IDC_EC_MAXFLATTRACKS            296
#define IDC_IT_MAXFLATSTRIPSINTRACK     296
#define IDC_EC_MAXFLATSTRIPSINTRACK     297

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         297
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
