//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlexStage4.rc
//
#define IDC_EC_TEST                     3
#define IDC_TS_AZS_SIMULATE             3
#define IDC_FH_START                    3
#define IDS_PROJNAME                    100
#define IDR_FLEXSTAGE                   102
#define IDD_MONITOR                     201
#define IDC_M_XPOS                      201
#define IDC_M_YPOS                      202
#define IDI_ICON64                      202
#define IDC_M_ZPOS                      203
#define IDI_ICON32                      203
#define IDC_M_XRED                      204
#define IDD_EDIT_CONFIG                 204
#define IDC_M_XGREEN                    205
#define IDD_TEST                        205
#define IDC_M_YRED                      206
#define IDD_FIND_HOME                   206
#define IDC_M_YGREEN                    207
#define IDC_M_ZRED                      208
#define IDI_FINDHOME_HOMED              208
#define IDC_M_ZGREEN                    209
#define IDI_FINDHOME_WARNING            209
#define IDD_EDIT_MACHINEDEFAULTS        209
#define IDC_M_HIDE                      210
#define IDI_FINDHOME_FINDING            210
#define IDC_M_TOGGLEMANUAL              211
#define IDC_M_RESET                     212
#define IDC_M_XYSPEED                   213
#define IDB_GAMEPAD                     213
#define IDC_M_ZSPEED                    214
#define IDC_M_LIGHT                     215
#define IDC_M_LIGHTLEVEL                216
#define IDC_M_10                        217
#define IDC_EC_BOARDID                  217
#define IDC_M_1                         218
#define IDC_EC_ACCELFACT                218
#define IDC_EC_INVLIMPOL                219
#define IDC_M_100                       219
#define IDC_EC_CONSTSPEEDACCEL          220
#define IDC_M_EXTRAS                    220
#define IDC_EC_XY_ACCEL                 221
#define IDC_M_GOTOORIGIN                221
#define IDC_EC_XY_ENC2MICRON            222
#define IDC_M_SETTOP                    222
#define IDC_EC_XY_LINESREV              223
#define IDC_M_GOTOP                     223
#define IDC_EC_XY_STEPSREV              224
#define IDC_M_GOBOTTOM                  224
#define IDC_EC_XY_MANMAXSPEED           225
#define IDC_M_PARKOBJ                   225
#define IDC_EC_XY_MANSPEEDMULT          226
#define IDC_M_HOME                      226
#define IDC_EC_XY_MAXSPEED              227
#define IDC_EC_XY_MANMAXSPEEDCHANGE     228
#define IDC_EC_Z_ENC2MICRON             229
#define IDC_EC_Z_STEPSREV               230
#define IDC_EC_Z_LINESREV               231
#define IDC_EC_Z_ACCEL                  232
#define IDC_EC_Z_MAXSPEED               233
#define IDC_EC_Z_MANSPEEDMULT           234
#define IDC_EC_Z_MANMAXSPEED            235
#define IDC_EC_Z_MANMAXSPEEDCHANGE      236
#define IDC_EC_STEPDIR                  237
#define IDC_EC_CWCCW                    238
#define IDC_EC_LIGHTLIMIT               239
#define IDC_EC_INVERTX                  240
#define IDC_EC_INVERTY                  241
#define IDC_TS_AZS_ZSCAN                241
#define IDC_EC_INVERTZ                  242
#define IDC_TS_AZS_X                    242
#define IDC_TS_AZS_ZSCANSPEED           243
#define IDC_EC_TURNOFFLIGHTTIME         243
#define IDC_TS_AZS_ZRESETSPEED          244
#define IDC_EC_Z_PARKPOS                244
#define IDC_FH_WARNING                  244
#define IDC_TS_AZS_ZRESETACC            245
#define IDC_EC_Z_BASETHICKNESS          245
#define IDC_FH_STATUS_IMAGE             245
#define IDC_TS_AZS_HSTEP                246
#define IDC_EMD_NAMELIST                246
#define IDC_EMD_REFPOSNAME              247
#define IDC_TS_AZS_HSTEPSPEED           248
#define IDC_EMD_REFPOSZ                 248
#define IDC_TS_AZS_HSTEPACC             249
#define IDC_EMD_REFPOSX                 249
#define IDC_TS_AZS_ZSCANDURATION        250
#define IDC_EMD_REFPOSY                 250
#define IDC_TS_AZS_HZSTEPTIME           251
#define IDC_EMD_REFPOSSET               251
#define IDC_TS_AZS_Y                    252
#define IDC_EMD_REFPOSDEL               252
#define IDC_TS_AZS_SAMPLINGTIME         253
#define IDC_EMD_Z_HOMINGSPEED           253
#define IDC_EMD_XY                      254
#define IDC_EMD_Z                       255
#define IDC_EMD_BOARDID                 256
#define IDC_EMD_STEPDIR                 257
#define IDC_EMD_CWCCW                   258
#define IDC_EMD_INVLIMPOL               259
#define IDC_EMD_LIGHTLIMIT              260
#define IDC_EMD_TURNOFFLIGHTTIME        261
#define IDC_EMD_XY_ENC2MICRON           262
#define IDC_EMD_XY_STEPSREV             263
#define IDC_EMD_XY_LINESREV             264
#define IDC_EMD_INVERTX                 265
#define IDC_EMD_INVERTY                 266
#define IDC_EMD_Z_ENC2MICRON            267
#define IDC_EMD_Z_STEPSREV              268
#define IDC_EMD_Z_LINESREV              269
#define IDC_EMD_INVERTZ                 270
#define IDC_EMD_Z_HOMINGXPOS            271
#define IDC_INTERACTIVEHOME             271
#define IDC_EMD_Z_HOMINGYPOS            272
#define IDC_EMD_XDIGDEC                 273
#define IDC_EMD_SETXDIGDEC              274
#define IDC_EMD_XDIGINC                 275
#define IDC_RADIO1                      275
#define IDC_EMD_SETXDIGINC              276
#define IDC_EMD_YDIGDEC                 281
#define IDC_EMD_SETYDIGDEC              282
#define IDC_EMD_YDIGINC                 283
#define IDC_EMD_SETYDIGINC              284
#define IDC_EMD_ZDIGDEC                 285
#define IDC_EMD_SETZDIGDEC              286
#define IDC_EMD_ZDIGINC                 287
#define IDC_EMD_SETZDIGINC              288
#define IDC_EMD_LDIGDEC                 289
#define IDC_EMD_SETLDIGDEC              290
#define IDC_EMD_LDIGINC                 291
#define IDC_EMD_SETLDIGINC              292
#define IDC_EMD_AUTOMAN                 293
#define IDC_EMD_SETAUTOMAN              294
#define IDC_EMD_SPEEDCHANGE             295
#define IDC_EMD_SETSPEEDCHANGE          296
#define IDC_EMD_XAXIS                   297
#define IDC_EMD_SETXAXIS                298
#define IDC_EMD_YAXIS                   299
#define IDC_EMD_SETYAXIS                300
#define IDC_EMD_ZAXIS                   301
#define IDC_EMD_SETZAXIS                302
#define IDC_EMD_LAXIS                   303
#define IDC_EMD_SETLAXIS                304

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         276
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
