//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BetaBrain.rc
//
#define IDC_AM_CONVERTEXT               101
#define IDC_AM_CONVERTSTG               102
#define IDC_AM_EXTX                     103
#define IDC_AM_EXTY                     104
#define IDC_AM_GOTOEXT                  105
#define IDC_AM_GOTOSTG                  106
#define IDC_AM_GRID                     107
#define IDC_AM_INITFILE                 108
#define IDC_AM_INITMAP                  109
#define IDC_AM_LOADCURRENT              110
#define IDC_AM_STGX                     111
#define IDC_AM_STGY                     112
#define IDC_AM_STOPSTG                  113
#define IDC_BM_CLUSTERDUMPS             114
#define IDC_BM_FOCUSFAULTS              115
#define IDC_BM_INTERRUPT                116
#define IDC_BM_PHOTOSEQUENCES           117
#define IDC_BM_STAGEFAULTS              118
#define IDC_BM_STARTTIME                119
#define IDC_BM_TIMETOCOMPLETION         120
#define IDC_BM_TODO                     121
#define IDC_BM_TOTALENTRIES             122
#define IDC_BM_TRACKS                   123
#define IDC_CDI_ENDDEPTH                124
#define IDC_BM_DISPLAYWAIT              124
#define IDC_CDI_FRAMES                  125
#define IDC_BM_FULLSPEED                125
#define IDC_CDI_ID0                     126
#define IDC_CDI_ID1                     127
#define IDC_CDI_ID2                     128
#define IDC_CDI_ID3                     129
#define IDC_CDI_POSX                    130
#define IDC_CDI_POSY                    131
#define IDC_CDI_STARTDEPTH              132
#define IDC_CDI_THRESHOLD               133
#define IDC_CDM_CLUSTERS                134
#define IDC_CDM_DEPTH                   135
#define IDC_CDM_ENDDEPTH                136
#define IDC_CDM_FRAME                   137
#define IDC_CDM_ID0                     138
#define IDC_CDM_ID1                     139
#define IDC_CDM_ID2                     140
#define IDC_CDM_ID3                     141
#define IDC_CDM_MOVING                  142
#define IDC_CDM_POSX                    143
#define IDC_CDM_POSY                    144
#define IDC_CDM_SETLIGHT                145
#define IDC_CDM_STARTDEPTH              146
#define IDC_CDM_TAKINGGRAINS            147
#define IDC_EC_AUTOLIGHTCONTROL         148
#define IDC_EC_CENTERSCANBACK           149
#define IDC_EC_CORRECTPREDS             149
#define IDC_EC_CHECKBOTTOM              150
#define IDC_EC_CENTERSB                 150
#define IDC_EC_CHECKTOP                 151
#define IDC_EC_PAUSEEACHFIELD           151
#define IDC_EC_CORRECTPRED              152
#define IDC_EC_E_BASETHICK              153
#define IDC_EC_E_BOTTOM_CLUSTERCONTRAST 154
#define IDC_EC_E_BOTTOM_CLUSTERTHRESH   155
#define IDC_EC_E_BOTTOM_ENDLAY          156
#define IDC_EC_E_BOTTOM_MAXFLATSTRIPS   157
#define IDC_EC_E_BOTTOM_MAXLAY          158
#define IDC_EC_E_BOTTOM_PIXMAX          159
#define IDC_EC_E_BOTTOM_PIXMIN          160
#define IDC_EC_E_BOTTOM_STARTLAY        161
#define IDC_EC_E_BOTTOMTHICK            162
#define IDC_EC_E_DEPTHCOHERLEN          163
#define IDC_EC_E_DISTCELLSIZE           164
#define IDC_EC_E_FOCUSTOL               165
#define IDC_EC_E_HEIGHT                 166
#define IDC_EC_E_HSPEED                 167
#define IDC_EC_E_LAMPDELAY              168
#define IDC_EC_E_LIGHTINCREMENT         169
#define IDC_EC_E_LONGDISTACC            170
#define IDC_EC_E_MAXCLUSTERS            171
#define IDC_EC_E_MAXFLATTRACKS          172
#define IDC_EC_E_MAXLIGHT               173
#define IDC_EC_E_MAXTRACKS              174
#define IDC_EC_E_MINGRAYLEV             175
#define IDC_EC_E_MINLIGHT               176
#define IDC_EC_E_MINSAMPLE              177
#define IDC_EC_E_PATHFILE               178
#define IDC_EC_E_POSTOL                 179
#define IDC_EC_E_RELAXTIME              180
#define IDC_EC_E_REWSPEED               181
#define IDC_EC_E_SCANSPEED              182
#define IDC_EC_E_SCANSTEP               183
#define IDC_EC_E_SHORTDISTACC           184
#define IDC_EC_E_SHRINKAGE              185
#define IDC_EC_E_SLOWDOWNLEN            186
#define IDC_EC_E_TARGETGRAYLEV          187
#define IDC_EC_E_THICKNESSTOL           188
#define IDC_EC_E_TOP_CLUSTERCONTRAST    189
#define IDC_EC_E_TOP_CLUSTERTHRESH      190
#define IDC_EC_E_TOP_ENDLAY             191
#define IDC_EC_E_TOP_MAXFLATSTRIPS      192
#define IDC_EC_E_TOP_MAXLAY             193
#define IDC_EC_E_TOP_PIXMAX             194
#define IDC_EC_E_TOP_PIXMIN             195
#define IDC_EC_E_TOP_STARTLAY           196
#define IDC_EC_E_TOPTHICK               197
#define IDC_EC_E_WAITLIMRESET           198
#define IDC_EC_E_WIDTH                  199
#define IDC_EC_E_XCENTERTOL             200
#define IDC_EC_E_XFIELDS                201
#define IDC_EC_E_XSTEP                  202
#define IDC_EC_E_XTOL                   203
#define IDC_EC_E_YCENTERTOL             204
#define IDC_EC_E_YFIELDS                205
#define IDC_EC_E_YSTEP                  206
#define IDC_EC_E_YTOL                   207
#define IDC_EC_E_ZONEXFIELDS            208
#define IDC_EC_E_ZONEYFIELDS            209
#define IDC_EC_E_ZSTATICTOL             210
#define IDC_EC_E_ZTOL                   211
#define IDC_EC_L_BASETHICK              212
#define IDC_EC_L_BOTTOM                 213
#define IDC_EC_L_BOTTOM_CLUSTERCONTRAST 214
#define IDC_EC_L_BOTTOM_CLUSTERTHRESH   215
#define IDC_EC_L_BOTTOM_ENDLAY          216
#define IDC_EC_L_BOTTOM_MAXFLATSTRIPS   217
#define IDC_EC_L_BOTTOM_MAXLAY          218
#define IDC_EC_L_BOTTOM_PIXMAX          219
#define IDC_EC_L_BOTTOM_PIXMIN          220
#define IDC_EC_L_BOTTOM_STARTLAY        221
#define IDC_EC_L_BOTTOMTHICK            222
#define IDC_EC_L_DEPTHCOHERLEN          223
#define IDC_EC_L_DISTCELLSIZE           224
#define IDC_EC_L_FOCUSTOL               225
#define IDC_EC_L_HEIGHT                 226
#define IDC_EC_L_HSPEED                 227
#define IDC_EC_L_LAMPDELAY              228
#define IDC_EC_L_LIGHTINCREMENT         229
#define IDC_EC_L_LONGDISTACC            230
#define IDC_EC_L_MAXCLUSTERS            231
#define IDC_EC_L_MAXFLATTRACKS          232
#define IDC_EC_L_MAXLIGHT               233
#define IDC_EC_L_MAXTRACKS              234
#define IDC_EC_L_MINGRAYLEV             235
#define IDC_EC_L_MINLIGHT               236
#define IDC_EC_L_MINSAMPLE              237
#define IDC_EC_L_PATHFILE               238
#define IDC_EC_L_POSTOL                 239
#define IDC_EC_L_RELAXTIME              240
#define IDC_EC_L_REWSPEED               241
#define IDC_EC_L_SCANSPEED              242
#define IDC_EC_L_SHORTDISTACC           243
#define IDC_EC_L_SHRINKAGE              244
#define IDC_EC_L_SLOWDOWNLEN            245
#define IDC_EC_L_TARGETGRAYLEV          246
#define IDC_EC_L_THICKNESSTOL           247
#define IDC_EC_L_TOP                    248
#define IDC_EC_L_TOP_CLUSTERCONTRAST    249
#define IDC_EC_L_TOP_CLUSTERTHRESH      250
#define IDC_EC_L_TOP_ENDLAY             251
#define IDC_EC_L_TOP_MAXFLATSTRIPS      252
#define IDC_EC_L_TOP_MAXLAY             253
#define IDC_EC_L_TOP_PIXMAX             254
#define IDC_EC_L_TOP_PIXMIN             255
#define IDC_EC_L_TOP_STARTLAY           256
#define IDC_EC_L_TOPTHICK               257
#define IDC_EC_L_WAITLIMRESET           258
#define IDC_EC_L_WIDTH                  259
#define IDC_EC_L_XFIELDS                260
#define IDC_EC_L_XSTEP                  261
#define IDC_EC_L_XTOL                   262
#define IDC_EC_L_YCENTERTOL             263
#define IDC_EC_L_YFIELDS                264
#define IDC_EC_L_YSTEP                  265
#define IDC_EC_L_YTOL                   266
#define IDC_EC_L_ZONEXFIELDS            267
#define IDC_EC_L_ZONEYFIELDS            268
#define IDC_EC_L_ZSTATICTOL             269
#define IDC_EC_L_ZTOL                   270
#define IDC_EC_PAUSE                    271
#define IDC_EC_RELATIVETHRESH           272
#define IDC_EC_RESETPATHFILE            273
#define IDC_EC_SCANBOTH                 274
#define IDC_EC_SCANBOTTOM               275
#define IDC_EC_SCANSTEP                 276
#define IDC_EC_SCANTOP                  277
#define IDC_EC_TAB                      278
#define IDC_EC_XCENTERTOL               279
#define IDC_EC_ZONESCANNING             280
#define IDC_MS_ABOUT                    281
#define IDC_MS_ASSISTEDMANUAL           282
#define IDC_MS_EXIT                     283
#define IDC_MS_EXTERNALCONTROLJOB       284
#define IDC_MS_HELP                     285
#define IDC_MS_USERDRIVEN               286
#define IDC_MS_USERJOB                  287
#define IDC_PSI_ENDDEPTH                288
#define IDC_PSI_FRAMES                  289
#define IDC_PSI_ID0                     290
#define IDC_PSI_ID1                     291
#define IDC_PSI_ID2                     292
#define IDC_PSI_ID3                     293
#define IDC_PSI_POSX                    294
#define IDC_PSI_POSY                    295
#define IDC_PSI_STARTDEPTH              296
#define IDC_PSI_XSIZE                   297
#define IDC_PSI_YSIZE                   298
#define IDC_PSM_DEPTH                   299
#define IDC_PSM_ENDDEPTH                300
#define IDC_PSM_FRAME                   301
#define IDC_PSM_ID0                     302
#define IDC_PSM_ID1                     303
#define IDC_PSM_ID2                     304
#define IDC_PSM_ID3                     305
#define IDC_PSM_MOVING                  306
#define IDC_PSM_POSX                    307
#define IDC_PSM_POSY                    308
#define IDC_PSM_SETLIGHT                309
#define IDC_PSM_STARTDEPTH              310
#define IDC_PSM_TAKINGIMAGE             311
#define IDC_SCI_GLOBALSLOPETOL          312
#define IDC_SCI_GOODSLOPETOL            313
#define IDC_SCI_ID0                     314
#define IDC_SCI_ID1                     315
#define IDC_SCI_ID2                     316
#define IDC_SCI_ID3                     317
#define IDC_SCI_POSX                    318
#define IDC_SCI_POSY                    319
#define IDC_SCI_SIDESLOPETOL            320
#define IDC_SCI_SLOPEX                  321
#define IDC_SCI_SLOPEY                  322
#define IDC_STM_BASETHICKNESS           323
#define IDC_STM_BOTTOM                  324
#define IDC_STM_BOTTOMTHICKNESS         325
#define IDC_STM_BOTTOMTRACKS            326
#define IDC_STM_CLUSTERS                327
#define IDC_STM_CROSSINGBASE            328
#define IDC_STM_FIELD                   329
#define IDC_STM_FOCUSING                330
#define IDC_STM_ID0                     331
#define IDC_STM_ID1                     332
#define IDC_STM_ID2                     333
#define IDC_STM_ID3                     334
#define IDC_STM_LAYER                   335
#define IDC_STM_LIGHTLEVEL              336
#define IDC_STM_MOVING                  337
#define IDC_STM_POSX                    338
#define IDC_STM_POSY                    339
#define IDC_STM_REFDEPTH                340
#define IDC_STM_SETLIGHT                341
#define IDC_STM_SLOPEX                  342
#define IDC_STM_SLOPEY                  343
#define IDC_STM_TAKINGGRAINS            344
#define IDC_STM_TONEXTFIELD             345
#define IDC_STM_TOP                     346
#define IDC_STM_TOPTHICKNESS            347
#define IDC_STM_TOPTRACKS               348
#define IDC_USC_CLUSTERDUMP             349
#define IDC_USC_PHOTOSEQ                350
#define IDC_USC_SCANTRACKS              351
#define IDD_ABOUT                       352
#define IDD_ASSISTED_MANUAL_SCANNING    353
#define IDD_BATCH_MONITOR               354
#define IDD_CLUSTER_DUMP_MONITOR        355
#define IDD_COMMAND_CLUSTERDUMP         356
#define IDD_COMMAND_CODE                357
#define IDD_COMMAND_PHOTOSEQ            358
#define IDD_COMMAND_SCANTRACKS          359
#define IDD_DIALOG1                     360
#define IDD_EDIT_CONFIG                 361
#define IDD_MAINSWITCH                  362
#define IDD_PHOTO_SEQUENCE_MONITOR      363
#define IDD_SCAN_TRACKS_MONITOR         364
#define IDI_ICON32                      365
#define IDI_ICON64                      366
#define IDR_BBRAIN                      367
#define IDS_PROJNAME                    368
#define IDC_EC_MAXCLUSTERS              377
#define IDC_EC_POSTOL                   378
#define IDC_EC_MAXTRACKS                379
#define IDC_EC_MAXFLATTRACKS            380
#define IDC_EC_BASETHICK                381
#define IDC_EC_TOPTHICK                 382
#define IDC_EC_BOTTOMTHICK              383
#define IDC_EC_DEPTHCOHERLEN            384
#define IDC_EC_DISTCELLSIZE             385
#define IDC_EC_WIDTH                    386
#define IDC_EC_HEIGHT                   387
#define IDC_EC_BASECROSSINGSPEED        388
#define IDC_EC_SCANNINGSPEED            389
#define IDC_EC_SCANNINGSTEP             390
#define IDC_EC_ZREWINDSPEED             391
#define IDC_EC_HORIZSPEED               392
#define IDC_EC_SHORTDISTACC             393
#define IDC_EC_LONGDISTACC              394
#define IDC_EC_FOCUSTOL                 395
#define IDC_EC_THICKNESSTOL             396
#define IDC_EC_SLOWDOWNLEN              397
#define IDC_EC_RELAXTIME                398
#define IDC_EC_WAITLIMRESET             399
#define IDC_EC_XSTEP                    400
#define IDC_EC_XTOLERANCE               401
#define IDC_EC_YSTEP                    402
#define IDC_EC_YTOLERANCE               403
#define IDC_EC_ZTOLERANCE               404
#define IDC_EC_ZSTATICTOLERANCE         405
#define IDC_EC_ZACC                     406
#define IDC_EC_ZONEXFIELDS              407
#define IDC_EC_MINLIGHT                 408
#define IDC_EC_MAXLIGHT                 409
#define IDC_EC_LIGHTINCREMENT           410
#define IDC_EC_TARGETGRAYLEV            411
#define IDC_EC_MINGRAYLEV               412
#define IDC_EC_LAMPDELAY                413
#define IDC_EC_ZONEYFIELDS              414
#define IDC_EC_MINSAMPLE                415
#define IDC_EC_CHKTOP                   416
#define IDC_EC_CHKBOTTOM                417
#define IDC_EC_YCENTERTOL               418
#define IDC_EC_SELPATH                  419
#define IDC_EC_RESETPATH                420
#define IDC_EC_PATH                     421
#define IDC_EC_XFIELDS                  422
#define IDC_EC_YFIELDS                  423
#define IDC_EC_TOP_CLUSTERCONTRAST      424
#define IDC_EC_TOP_CLUSTERTHRESH        425
#define IDC_EC_TOP_MINPIX               426
#define IDC_EC_TOP_MAXPIX               427
#define IDC_EC_TOP_STARTLAYER           428
#define IDC_EC_TOP_MINLAYERS            429
#define IDC_EC_TOP_MAXLAYERS            430
#define IDC_EC_TOP_MAXFLATSTRIPS        431
#define IDC_EC_BOTTOM_CLUSTERCONTRAST   432
#define IDC_EC_BOTTOM_CLUSTERTHRESH     433
#define IDC_EC_BOTTOM_MINPIX            434
#define IDC_EC_BOTTOM_MAXPIX            435
#define IDC_EC_BOTTOM_STARTLAYER        436
#define IDC_EC_BOTTOM_MINLAYERS         437
#define IDC_EC_BOTTOM_MAXLAYERS         438
#define IDC_EC_BOTTOM_MAXFLATSTRIPS     439
#define IDC_EC_SHRINKAGE                440

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         443
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
