#if !defined(AFX_AXEMUDISPLAY_H__D68B0271_FBFD_4816_BDCB_8E2D46C5034B__INCLUDED_)
#define AFX_AXEMUDISPLAY_H__D68B0271_FBFD_4816_BDCB_8E2D46C5034B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAxEmuDisplay wrapper class

class CAxEmuDisplay : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAxEmuDisplay)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8bc5e964, 0x78dc, 0x4e3b, { 0x94, 0x26, 0x85, 0xd0, 0xfc, 0x2e, 0xd7, 0x89 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetBkgndColor();
	void SetBkgndColor(unsigned long);
	unsigned long GetBoundColor();
	void SetBoundColor(unsigned long);
	BOOL GetMouseEnabled();
	void SetMouseEnabled(BOOL);
	BOOL GetUseRightMouseButton();
	void SetUseRightMouseButton(BOOL);
	float GetMouseRotationMultiplier();
	void SetMouseRotationMultiplier(float);
	float GetMouseZoomMultiplier();
	void SetMouseZoomMultiplier(float);

// Operations
public:
	BOOL SetBounds(float MinX, float MaxX, float MinY, float MaxY, float MinZ, float MaxZ);
	void Clear();
	BOOL AddPlane(float Z);
	BOOL AddPoint(float X, float Y, float Z, float R, float G, float B);
	BOOL AddPointAutoColor(float X, float Y, float Z);
	BOOL AddSegment(float StartX, float StartY, float StartZ, float StartR, float StartG, float StartB, float EndX, float EndY, float EndZ, float EndR, float EndG, float EndB);
	BOOL AddSegmentAutoColor(float StartX, float StartY, float StartZ, float EndX, float EndY, float EndZ);
	BOOL StartNewSegment();
	BOOL EndNewSegment();
	BOOL AddVertexToSegment(float X, float Y, float Z, float R, float G, float B);
	BOOL AddVertexToSegmentAutoColor(float X, float Y, float Z);
	void SetMouseFunction(short Function);
	short GetMouseFunction();
	BOOL SetCameraPos(float X, float Y, float Z);
	float GetCameraPosX();
	float GetCameraPosY();
	float GetCameraPosZ();
	BOOL SetInterestingPoint(float X, float Y, float Z);
	float GetInterestingPointX();
	float GetInterestingPointY();
	float GetInterestingPointZ();
	BOOL SetCameraDist(float Distance);
	float GetCameraDist();
	BOOL SetCameraDirNorm(float DX, float DY, float DZ, float NX, float NY, float NZ);
	float GetCameraDirX();
	float GetCameraDirY();
	float GetCameraDirZ();
	float GetCameraNormX();
	float GetCameraNormY();
	float GetCameraNormZ();
	BOOL SetZoom(float Zoom);
	float GetZoom();
	void SetDefaultView();
	BOOL Render();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXEMUDISPLAY_H__D68B0271_FBFD_4816_BDCB_8E2D46C5034B__INCLUDED_)
