//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TSReconstruct.rc
//
#define IDC_MS_INTERACTIVE              3
#define IDC_IR_DEFAULTVIEW              3
#define IDC_BP_START                    3
#define IDC_MP_MATCH                    3
#define IDC_MS_BATCH                    4
#define IDC_IR_SEL_ALIGNMENTDATA        4
#define IDC_BP_STOP                     4
#define IDC_MP_SHUFFLE                  4
#define IDC_IR_SEL_LISTFILE             5
#define IDC_BP_CLEARLOG                 5
#define IDC_IR_SEL_OUTPUTFILE           6
#define IDC_IR_SEL_REPORTFILE           7
#define IDC_IR_RECONSTRUCT              8
#define IDC_IR_EDITCONFIG               9
#define IDC_IR_SAVE                     10
#define IDC_IR_LOAD                     11
#define IDC_IR_LOAD_RECONSTRUCTION      12
#define IDC_IR_TOPOLOGY                 13
#define IDC_IR_BATCH                    14
#define IDC_IR_MATCHPRED                14
#define IDC_IR_SAVECONFIG               15
#define IDS_PROJNAME                    100
#define IDR_TSRECON                     102
#define IDI_ICON64                      201
#define IDD_MAINSWITCH                  201
#define IDC_MS_ABOUT                    201
#define IDI_ICON32                      202
#define IDC_EC_MINSEGS                  202
#define IDD_INTERACTIVE                 202
#define IDC_EC_PLATECROSSING            203
#define IDD_ABOUT                       204
#define IDC_EC_INPLATEDSLOPE            204
#define IDC_EC_INPLATEDPOS              205
#define IDC_IR_ROTATE                   205
#define IDD_SELECT_EVENT                205
#define IDC_EC_INPLATEGROSSDPOS         206
#define IDC_IR_ZOOM                     206
#define IDD_MATCH_PREDICTION            206
#define IDC_EC_INPLATEMAXITERS          207
#define IDC_IR_SHOWRAW                  207
#define IDC_EC_OFFPLATEDSLOPE           208
#define IDC_IR_SHOWSEGMENTS             208
#define IDC_EC_OFFPLATEDPOS             209
#define IDC_IR_EALIGNMENTDATA           209
#define IDC_EC_OFFPLATEGROSSDPOS        210
#define IDC_IR_ELISTFILE                210
#define IDI_RED                         210
#define IDC_EC_OFFPLATEMAXITERS         211
#define IDC_IR_EOUTPUTDATA              211
#define IDD_BATCH                       211
#define IDI_BLUE                        211
#define IDD_EDIT_CONFIG                 212
#define IDC_EC_MAXMISSINGSEGS           212
#define IDC_IR_EREPORTDATA              212
#define IDI_GREEN                       212
#define IDC_EC_INFIELDDSLOPE            213
#define IDC_IR_SHOWTRACKS               213
#define IDI_YELLOW                      213
#define IDC_IR_SCREEN                   214
#define IDC_EC_INFIELDDPOS              214
#define IDI_CYAN                        214
#define IDC_EC_OFFFIELDDSLOPE           215
#define IDC_IR_SHOWTRACKSEGS            215
#define IDI_MAGENTA                     215
#define IDC_EC_OFFFIELDDPOS             216
#define IDC_EC_MERGE                    217
#define IDC_EC_DISCARDSHORTER           218
#define IDC_EC_DISCARDWORSE             219
#define IDC_IR_ACTION                   219
#define IDC_EC_PASSTHRU_RADIUS          220
#define IDC_IR_ACTIONPROGRESS           220
#define IDC_EC_PASSTHRU_ANGLE           221
#define IDC_SE_LIST                     221
#define IDC_EC_PASSTHRU_OUTLENGTH       222
#define IDC_IR_FROMVERTEX               222
#define IDC_EC_VERTEX_XYTOL             223
#define IDC_MP_SLOPETOL                 223
#define IDC_IR_PASSINGTHROUGH           223
#define IDC_EC_VERTEX_XYTOLINCREASE     224
#define IDC_MP_LIST                     224
#define IDC_EC_VERTEX_OVERLENGTH        225
#define IDC_MP_SLOPEXCOMBO              225
#define IDC_EC_VERTEX_LOWESTZ           226
#define IDC_MP_SLOPEYCOMBO              226
#define IDC_EC_VERTEX_MERGEXYTOL        227
#define IDC_BP_RAWDATA                  227
#define IDC_EC_VERTEX_MERGEZTOL         228
#define IDC_BP_FULLREPROCESS            228
#define IDC_EC_MAXREMEASURESINSEG       229
#define IDC_BP_PARTIALREPROCESS         229
#define IDC_EC_INPLATEGROSSDSLOPE       230
#define IDC_IR_ID                       230
#define IDC_EC_OFFPLATEGROSSDSLOPE      231
#define IDC_IR_NOTES                    231
#define IDC_EC_INPLATEPOSPRESCAN        232
#define IDC_EC_OFFPLATEPOSPRESCAN       233
#define IDC_EC_LOWESTPRESCANPEAK        234
#define IDC_EC_MINSEGSRECOVERY          235
#define IDC_EC_VERTEX_EXTRAPOLATION     236
#define IDC_EC_VERTEX_REC_EXTRAPOLATION 237
#define IDC_EC_FINALALIGNMENTENABLE     238
#define IDC_EC_FINALITERATIONS          239
#define IDC_EC_FINALUSEPOS              240
#define IDC_EC_FINALSLOPEMEASURES       240
#define IDC_EC_FINALUSEPOSSLOPES        241
#define IDC_EC_FINALMAXDIFF             242
#define IDC_EC_FINALMINDIFF             243
#define IDC_EC_FINALMINENTRIES          244
#define IDC_EC_FINALMAXACCRMS           245
#define IDC_BP_ALIGNMENTDATA            273
#define IDC_BP_EALIGNMENTDATA           274
#define IDC_BP_STATUS                   275
#define IDC_BP_PERCENT                  276
#define IDC_BP_PROGRESS                 277
#define IDC_BP_ELAPSEDTIME              279
#define IDC_BP_TIMETOCOMPLETION         281
#define IDC_BP_MSGLOG                   283
#define IDC_BP_LISTFILE                 284
#define IDC_BP_ELISTFILE                285
#define IDC_BP_ERRORCOUNT               286

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         243
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
