// Objective.idl : IDL source for Objective.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Objective.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\Common\Connection.h";
import "..\Common\Config.h";
import "..\Common\GUIdefs.h";
import "..\Common\CameraSpec.h";
import "..\Common\CameraSpec2.h";
	[
		object,
		uuid(C022EEAD-748A-11D3-A47B-E89C0BCE9720),
	
		helpstring("ISySalObject Interface"),
		pointer_default(unique)
	]
	interface ISySalObject : IUnknown
	{
		[helpstring("method SetName")] HRESULT SetName(ConnectionName name);
		[helpstring("method GetName")] HRESULT GetName(ConnectionName name);
		[helpstring("method SetConfig")] HRESULT SetConfig(SySalConfig *pConfig);
		[helpstring("method GetConfig")] HRESULT GetConfig(SySalConfig *pConfig);
		[helpstring("method EditConfig")] HRESULT EditConfig(SySalConfig *pConfig, HSySalHANDLE hWnd);
		[helpstring("method EnableMonitor")] HRESULT EnableMonitor(boolean bEnable);
		[helpstring("method GetNumberOfConnections")] HRESULT GetNumberOfConnections(int *pNumber);
		[helpstring("method SetConnection")] HRESULT SetConnection(int n, SySalConnection connection);
		[helpstring("method GetConnection")] HRESULT GetConnection(int n, SySalConnection *pConnection);
		[helpstring("method GetIcon")] HRESULT GetIcon(int n, HSySalHICON *pHICON);
		[helpstring("method GetClassName")] HRESULT GetClassName(ConnectionName name);
		[helpstring("method SyncExec")] HRESULT SyncExec();
		[helpstring("method AsyncExec")] HRESULT AsyncExec(HSySalHANDLE HNotifyStatusChangeEvent);
		[helpstring("method AsyncCheckStatus")] HRESULT AsyncCheckStatus(long *pStatus);
		[helpstring("method AsyncWait")] HRESULT AsyncWait();
		[helpstring("method AsyncPause")] HRESULT AsyncPause();
		[helpstring("method AsyncStop")] HRESULT AsyncStop();
		[helpstring("method AsyncResume")] HRESULT AsyncResume();
		[helpstring("method IsReady")] HRESULT IsReady(long *pWrongConn, long *pRetCode);
	};
	[
		object,
		uuid(E056524D-7CFD-11D3-A47C-AC71B6A41C20),
	
		helpstring("IObjective Interface"),
		pointer_default(unique)
	]
	interface IObjective : IUnknown
	{
		[helpstring("method SetSpecs")] HRESULT SetSpecs(CameraSpec Spec);
		[helpstring("method GetSpecs")] HRESULT GetSpecs(CameraSpec *pSpec);
	};
	[
		object,
		uuid(9e7b8b40-7b28-4f5f-809f-002cbac97241),
	
		helpstring("IObjective2 Interface"),
		pointer_default(unique)
	]
	interface IObjective2 : IObjective
	{
		[helpstring("method SetSpecs2")] HRESULT SetSpecs2(CameraSpec2 Spec);
		[helpstring("method GetSpecs2")] HRESULT GetSpecs2(CameraSpec2 *pSpec);
	};

[
	uuid(E0565240-7CFD-11D3-A47C-AC71B6A41C20),
	version(1.0),
	helpstring("Objective 1.0 Type Library")
]
library OBJECTIVELib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(E056524E-7CFD-11D3-A47C-AC71B6A41C20),
		helpstring("Objective Class")
	]
	coclass Objective
	{
		[default] interface ISySalObject;
		interface IObjective;
	};
};
