	TITLE	D:\SySal2\SmartTracker7\EditConfig.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT ??_C@_0BB@NAAD@Magellan?5MSWHEEL?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_06FPAF@MouseZ?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BA@CLBL@MSWHEEL_ROLLMSG?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BF@DLPD@MSH_WHEELSUPPORT_MSG?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BF@ODOJ@MSH_SCROLL_LINES_MSG?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BP@EDBF@Object?5created?5on?5thread?5?$DN?5?$CFd?6?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_05FGFK@CLSID?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_00A@?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_03DMDD@?5?9?5?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_09MOFL@Interface?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0M@FNJL@?$CICLSID?$DP?$DP?$DP?$CJ?5?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_09DLIL@?5?9?5failed?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_01BJG@?6?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BO@DOIJ@CPropertyHelper?3?3GetProperty?6?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BO@EJEI@CPropertyHelper?3?3PutProperty?6?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0FH@HFKE@CComClassFactory?3?5asked?5for?5non?5@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0M@CACD@Trial?5Error?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0BA@LLJB@Too?5many?5trials?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0CL@NNLD@Bottom?5layer?5must?5be?5higher?5than@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_01KMAE@?0?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_02MECO@?$CFd?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0CK@IJH@Triggers?5must?5be?5comma?9separated@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_03BJDM@Top?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_06LHCD@Bottom?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_07LCDE@Trigger?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??_C@_0P@NFOI@HelpConfig?4htm?$AA@
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ??0Vector@@QAE@MMM@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CSmartTrackerClass@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?_GetRawUnknown@CSmartTrackerClass@@QAEPAUIUnknown@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?_GetEntries@CSmartTrackerClass@@SGPBU_ATL_INTMAP_ENTRY@ATL@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCSmartTrackerClass@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0ITracker3@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0ISySalObject@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0ITracker2@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0IUnknown@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0ITracker@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCDragListBox@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCToolBarCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCStatusBarCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0CListCtrl@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCListCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?InsertItem@CListCtrl@@QAEHHPBD@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?DeleteItem@CListCtrl@@QAEHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GetNextItem@CListCtrl@@QBEHHH@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCTreeCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCHotKeyCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCSpinButtonCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCSliderCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCProgressCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCHeaderCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??BCImageList@@QBEPAU_IMAGELIST@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GetSafeHandle@CImageList@@QBEPAU_IMAGELIST@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCTabCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCAnimateCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCRichEditCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GetSelectionMark@CListCtrl@@QAEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCReBarCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CReBarCtrl@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCComboBoxEx@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCIPAddressCtrl@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0CEditConfig@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCEditConfig@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CEditConfig@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?OnAdd@CEditConfig@@IAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?OnDel@CEditConfig@@IAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?OnInitDialog@CEditConfig@@MAEHXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?OnTest@CEditConfig@@IAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CTestDlg@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?OnHelp@CEditConfig@@IAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComPtr@UIUnknown@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$CComPtr@UIUnknown@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??B?$CComPtr@UIUnknown@@@ATL@@QBEPAUIUnknown@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??I?$CComPtr@UIUnknown@@@ATL@@QAEPAPAUIUnknown@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??8?$CComPtr@UIUnknown@@@ATL@@QBE_NPAUIUnknown@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComPtr@UIPersistStream@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$CComPtr@UIPersistStream@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??B?$CComPtr@UIPersistStream@@@ATL@@QBEPAUIPersistStream@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??I?$CComPtr@UIPersistStream@@@ATL@@QAEPAPAUIPersistStream@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?InternalAddRef@?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAEKXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?InternalRelease@?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAEKXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Lock@?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Unlock@?$CComObjectRootEx@VCComMultiThreadModel@ATL@@@ATL@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComPtr@UITypeInfo@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComPtr@UITypeInfo@@@ATL@@QAE@ABV01@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$CComPtr@UITypeInfo@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??B?$CComPtr@UITypeInfo@@@ATL@@QBEPAUITypeInfo@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??I?$CComPtr@UITypeInfo@@@ATL@@QAEPAPAUITypeInfo@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??C?$CComPtr@UITypeInfo@@@ATL@@QBEPAV?$_NoAddRefReleaseOnCComPtr@UITypeInfo@@@1@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??4?$CComPtr@UITypeInfo@@@ATL@@QAEPAUITypeInfo@@PAU2@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Detach@?$CComPtr@UITypeInfo@@@ATL@@QAEPAUITypeInfo@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0?$CComPtr@UITypeInfo2@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1?$CComPtr@UITypeInfo2@@@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??B?$CComPtr@UITypeInfo2@@@ATL@@QBEPAUITypeInfo2@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??I?$CComPtr@UITypeInfo2@@@ATL@@QAEPAPAUITypeInfo2@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?QueryInterface@IUnknown@@QAGJPAPAUITypeInfo2@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCNotSupportedException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CNotSupportedException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CNotSupportedException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??1CSimpleException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CSimpleException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??1CException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??1CObject@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CObject@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCMemoryException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CMemoryException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CMemoryException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCSimpleException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCFileException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CFileException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CFileException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCArchiveException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CArchiveException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CArchiveException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCObject@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCOleException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1COleException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7COleException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCNoTrackObject@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CNoTrackObject@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCScrollBar@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCEdit@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCComboBox@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCCheckListBox@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CCheckListBox@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCListBox@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCButton@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCStatic@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCMenu@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CMenu@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CMenu@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCRgn@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CRgn@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CRgn@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??1CGdiObject@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CGdiObject@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCPalette@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CPalette@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CPalette@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCBitmap@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CBitmap@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CBitmap@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCFont@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CFont@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CFont@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCBrush@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CBrush@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CBrush@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCPen@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CPen@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CPen@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCGdiObject@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_GCUserException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CUserException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CUserException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_GCResourceException@@UAEPAXI@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1CResourceException@@UAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CResourceException@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?EndModalState@CWnd@@UAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?BeginModalState@CWnd@@UAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Dump@CObject@@UBEXAAVCDumpContext@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?AssertValid@CObject@@UBEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Serialize@CObject@@UAEXAAVCArchive@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT __GUID_00020412_0000_0000_c000_000000000046
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ?Unlock@CComAutoCriticalSection@ATL@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Lock@CComAutoCriticalSection@ATL@@QAEXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Decrement@CComMultiThreadModel@ATL@@SGKPAJ@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?Increment@CComMultiThreadModel@ATL@@SGKPAJ@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??BCString@@QBEPBDXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CEditConfig@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CIPAddressCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CComboBoxEx@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??0CComboBox@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CComboBox@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?FromHandle@CPalette@@SGPAV1@PAUHPALETTE__@@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CReBarCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??0CPoint@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CRichEditCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CAnimateCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??0CSize@@QAE@K@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CTabCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?GetSafeHdc@CDC@@QBEPAUHDC__@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?GetSafeHandle@CGdiObject@@QBEPAXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CHeaderCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CProgressCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CSliderCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CSpinButtonCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CHotKeyCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CTreeCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CListCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_7CStatusBarCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ?GetSafeHwnd@CWnd@@QBEPAUHWND__@@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CToolBarCtrl@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??3CObject@@SGXPAX@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CDragListBox@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??0CListBox@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??_7CListBox@@6B@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??1CComAutoCriticalSection@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0CComAutoCriticalSection@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??0CComObjectRootBase@ATL@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?_entries@?1??_GetEntries@CSmartTrackerClass@@SGPBU_ATL_INTMAP_ENTRY@ATL@@XZ@4QBU34@B
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT __GUID_c022eead_748a_11d3_a47b_e89c0bce9720
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT __GUID_7a9e779c_aa32_4565_8e69_5f1bc4e362b7
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT __GUID_67a71430_f2e4_42ae_8910_28279a7616d6
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT __GUID_e416c46d_7f68_11d3_a47c_fa1e4afa2721
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
;	COMDAT ?InternalQueryInterface@CComObjectRootBase@ATL@@SGJPAXPBU_ATL_INTMAP_ENTRY@2@ABU_GUID@@PAPAX@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?_Cache@CComObjectRootBase@ATL@@SGJPAXABU_GUID@@PAPAXK@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ?UpdateRegistryFromResourceD@CComModule@ATL@@QAGJIHPAU_ATL_REGMAP_ENTRY@2@@Z
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT ??1AFX_MAINTAIN_STATE2@@QAE@XZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif
PUBLIC	?OnAdd@CEditConfig@@IAEXXZ			; CEditConfig::OnAdd
PUBLIC	?OnDel@CEditConfig@@IAEXXZ			; CEditConfig::OnDel
PUBLIC	?OnTest@CEditConfig@@IAEXXZ			; CEditConfig::OnTest
PUBLIC	?OnHelp@CEditConfig@@IAEXXZ			; CEditConfig::OnHelp
PUBLIC	?_messageEntries@CEditConfig@@0QBUAFX_MSGMAP_ENTRY@@B ; CEditConfig::_messageEntries
PUBLIC	?messageMap@CEditConfig@@1UAFX_MSGMAP@@B	; CEditConfig::messageMap
PUBLIC	?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ ; CEditConfig::_GetBaseMessageMap
CONST	SEGMENT
?messageMap@CEditConfig@@1UAFX_MSGMAP@@B DD FLAT:?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ ; CEditConfig::messageMap
	DD	FLAT:?_messageEntries@CEditConfig@@0QBUAFX_MSGMAP_ENTRY@@B
?_messageEntries@CEditConfig@@0QBUAFX_MSGMAP_ENTRY@@B DD 0111H ; CEditConfig::_messageEntries
	DD	00H
	DD	0daH
	DD	0daH
	DD	0cH
	DD	FLAT:?OnAdd@CEditConfig@@IAEXXZ
	DD	0111H
	DD	00H
	DD	0dbH
	DD	0dbH
	DD	0cH
	DD	FLAT:?OnDel@CEditConfig@@IAEXXZ
	DD	0111H
	DD	00H
	DD	03H
	DD	03H
	DD	0cH
	DD	FLAT:?OnTest@CEditConfig@@IAEXXZ
	DD	0111H
	DD	00H
	DD	04H
	DD	04H
	DD	0cH
	DD	FLAT:?OnHelp@CEditConfig@@IAEXXZ
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	??_7CListCtrl@@6B@				; CListCtrl::`vftable'
PUBLIC	??_GCListCtrl@@UAEPAXI@Z			; CListCtrl::`scalar deleting destructor'
PUBLIC	??_ECListCtrl@@UAEPAXI@Z			; CListCtrl::`vector deleting destructor'
PUBLIC	??0CEditConfig@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z ; CEditConfig::CEditConfig
PUBLIC	?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z ; CEditConfig::DoDataExchange
PUBLIC	?OnInitDialog@CEditConfig@@MAEHXZ		; CEditConfig::OnInitDialog
PUBLIC	?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ ; CEditConfig::GetMessageMap
PUBLIC	??_7CEditConfig@@6B@				; CEditConfig::`vftable'
PUBLIC	??_GCEditConfig@@UAEPAXI@Z			; CEditConfig::`scalar deleting destructor'
PUBLIC	??_ECEditConfig@@UAEPAXI@Z			; CEditConfig::`vector deleting destructor'
PUBLIC	?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z	; CWnd::DoDataExchange
PUBLIC	?BeginModalState@CWnd@@UAEXXZ			; CWnd::BeginModalState
PUBLIC	?EndModalState@CWnd@@UAEXXZ			; CWnd::EndModalState
PUBLIC	?Serialize@CObject@@UAEXAAVCArchive@@@Z		; CObject::Serialize
PUBLIC	?AssertValid@CObject@@UBEXXZ			; CObject::AssertValid
PUBLIC	?Dump@CObject@@UBEXAAVCDumpContext@@@Z		; CObject::Dump
PUBLIC	??_C@_00A@?$AA@					; `string'
EXTRN	?ContinueModal@CWnd@@UAEHXZ:NEAR		; CWnd::ContinueModal
EXTRN	?EndModalLoop@CWnd@@UAEXH@Z:NEAR		; CWnd::EndModalLoop
EXTRN	?DrawItem@CListCtrl@@UAEXPAUtagDRAWITEMSTRUCT@@@Z:NEAR ; CListCtrl::DrawItem
EXTRN	??1CListCtrl@@UAE@XZ:NEAR			; CListCtrl::~CListCtrl
EXTRN	?OnCommand@CWnd@@MAEHIJ@Z:NEAR			; CWnd::OnCommand
EXTRN	?OnChildNotify@CListCtrl@@MAEHIIJPAJ@Z:NEAR	; CListCtrl::OnChildNotify
EXTRN	?OnNotify@CWnd@@MAEHIJPAJ@Z:NEAR		; CWnd::OnNotify
EXTRN	?GetMessageMap@CListCtrl@@MBEPBUAFX_MSGMAP@@XZ:NEAR ; CListCtrl::GetMessageMap
EXTRN	??0CString@@QAE@XZ:NEAR				; CString::CString
EXTRN	??4CString@@QAEABV0@PBD@Z:NEAR			; CString::operator=
EXTRN	?OnCmdMsg@CCmdTarget@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:NEAR ; CCmdTarget::OnCmdMsg
EXTRN	?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z:NEAR	; CCmdTarget::IsInvokeAllowed
EXTRN	?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z:NEAR ; CCmdTarget::GetDispatchIID
EXTRN	?GetTypeInfoCount@CCmdTarget@@UAEIXZ:NEAR	; CCmdTarget::GetTypeInfoCount
EXTRN	?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ:NEAR ; CCmdTarget::GetTypeLibCache
EXTRN	?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z:NEAR ; CCmdTarget::GetTypeLib
EXTRN	?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ:NEAR ; CCmdTarget::GetCommandMap
EXTRN	?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ:NEAR ; CCmdTarget::GetDispatchMap
EXTRN	?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ:NEAR ; CCmdTarget::GetConnectionMap
EXTRN	?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ:NEAR ; CCmdTarget::GetInterfaceMap
EXTRN	?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ:NEAR ; CCmdTarget::GetEventSinkMap
EXTRN	?OnCreateAggregates@CCmdTarget@@UAEHXZ:NEAR	; CCmdTarget::OnCreateAggregates
EXTRN	?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z:NEAR ; CCmdTarget::GetInterfaceHook
EXTRN	??1CString@@QAE@XZ:NEAR				; CString::~CString
EXTRN	?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ:NEAR ; CWnd::GetSuperWndProcAddr
EXTRN	?PreTranslateMessage@CWnd@@UAEHPAUtagMSG@@@Z:NEAR ; CWnd::PreTranslateMessage
EXTRN	?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z:NEAR ; CWnd::OnAmbientProperty
EXTRN	?WindowProc@CWnd@@MAEJIIJ@Z:NEAR		; CWnd::WindowProc
EXTRN	?OnWndMsg@CWnd@@MAEHIIJPAJ@Z:NEAR		; CWnd::OnWndMsg
EXTRN	?DefWindowProcA@CWnd@@MAEJIIJ@Z:NEAR		; CWnd::DefWindowProcA
EXTRN	?PostNcDestroy@CWnd@@MAEXXZ:NEAR		; CWnd::PostNcDestroy
EXTRN	?OnChildNotify@CWnd@@MAEHIIJPAJ@Z:NEAR		; CWnd::OnChildNotify
EXTRN	?CheckAutoCenter@CWnd@@UAEHXZ:NEAR		; CWnd::CheckAutoCenter
EXTRN	?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z:NEAR ; CCmdTarget::GetExtraConnectionPoints
EXTRN	?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z:NEAR ; CCmdTarget::GetConnectionHook
EXTRN	?IsFrameWnd@CWnd@@UBEHXZ:NEAR			; CWnd::IsFrameWnd
EXTRN	?OnFinalRelease@CWnd@@UAEXXZ:NEAR		; CWnd::OnFinalRelease
EXTRN	?SetOccDialogInfo@CWnd@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z:NEAR ; CWnd::SetOccDialogInfo
EXTRN	??0CWnd@@QAE@XZ:NEAR				; CWnd::CWnd
EXTRN	?GetRuntimeClass@CDialog@@UBEPAUCRuntimeClass@@XZ:NEAR ; CDialog::GetRuntimeClass
EXTRN	?PreSubclassWindow@CWnd@@UAEXXZ:NEAR		; CWnd::PreSubclassWindow
EXTRN	?Create@CWnd@@UAEHPBD0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z:NEAR ; CWnd::Create
EXTRN	??0CDialog@@QAE@IPAVCWnd@@@Z:NEAR		; CDialog::CDialog
EXTRN	?DoModal@CDialog@@UAEHXZ:NEAR			; CDialog::DoModal
EXTRN	?OnSetFont@CDialog@@UAEXPAVCFont@@@Z:NEAR	; CDialog::OnSetFont
EXTRN	?OnOK@CDialog@@MAEXXZ:NEAR			; CDialog::OnOK
EXTRN	?OnCancel@CDialog@@MAEXXZ:NEAR			; CDialog::OnCancel
EXTRN	??1CDialog@@UAE@XZ:NEAR				; CDialog::~CDialog
EXTRN	?PreTranslateMessage@CDialog@@UAEHPAUtagMSG@@@Z:NEAR ; CDialog::PreTranslateMessage
EXTRN	?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:NEAR ; CDialog::OnCmdMsg
EXTRN	?CheckAutoCenter@CDialog@@UAEHXZ:NEAR		; CDialog::CheckAutoCenter
EXTRN	?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z:NEAR ; CDialog::SetOccDialogInfo
EXTRN	?PreInitDialog@CDialog@@MAEXXZ:NEAR		; CDialog::PreInitDialog
EXTRN	?DestroyWindow@CWnd@@UAEHXZ:NEAR		; CWnd::DestroyWindow
EXTRN	?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTA@@@Z:NEAR ; CWnd::PreCreateWindow
EXTRN	?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z:NEAR	; CWnd::CalcWindowRect
EXTRN	?GetRuntimeClass@CListCtrl@@UBEPAUCRuntimeClass@@XZ:NEAR ; CListCtrl::GetRuntimeClass
EXTRN	?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOA@@@Z:NEAR ; CWnd::OnToolHitTest
EXTRN	?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z:NEAR ; CWnd::GetScrollBarCtrl
EXTRN	__except_list:DWORD
EXTRN	___CxxFrameHandler:NEAR
EXTRN	?WinHelpA@CWnd@@UAEXKI@Z:NEAR			; CWnd::WinHelpA
;	COMDAT ??_C@_00A@?$AA@
; File D:\Program Files\Microsoft Visual Studio\VC98\MFC\INCLUDE\afxcmn.inl
_BSS	SEGMENT
??_C@_00A@?$AA@ DB 01H DUP (?)				; `string'
_BSS	ENDS
;	COMDAT ??_7CListCtrl@@6B@
CONST	SEGMENT
??_7CListCtrl@@6B@ DD FLAT:?GetRuntimeClass@CListCtrl@@UBEPAUCRuntimeClass@@XZ ; CListCtrl::`vftable'
	DD	FLAT:??_ECListCtrl@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CObject@@UBEXXZ
	DD	FLAT:?Dump@CObject@@UBEXAAVCDumpContext@@@Z
	DD	FLAT:?OnCmdMsg@CCmdTarget@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z
	DD	FLAT:?OnFinalRelease@CWnd@@UAEXXZ
	DD	FLAT:?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z
	DD	FLAT:?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z
	DD	FLAT:?GetTypeInfoCount@CCmdTarget@@UAEIXZ
	DD	FLAT:?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ
	DD	FLAT:?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z
	DD	FLAT:?GetMessageMap@CListCtrl@@MBEPBUAFX_MSGMAP@@XZ
	DD	FLAT:?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ
	DD	FLAT:?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ
	DD	FLAT:?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ
	DD	FLAT:?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ
	DD	FLAT:?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ
	DD	FLAT:?OnCreateAggregates@CCmdTarget@@UAEHXZ
	DD	FLAT:?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z
	DD	FLAT:?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z
	DD	FLAT:?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z
	DD	FLAT:?PreSubclassWindow@CWnd@@UAEXXZ
	DD	FLAT:?Create@CWnd@@UAEHPBD0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z
	DD	FLAT:?DestroyWindow@CWnd@@UAEHXZ
	DD	FLAT:?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTA@@@Z
	DD	FLAT:?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z
	DD	FLAT:?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOA@@@Z
	DD	FLAT:?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z
	DD	FLAT:?WinHelpA@CWnd@@UAEXKI@Z
	DD	FLAT:?ContinueModal@CWnd@@UAEHXZ
	DD	FLAT:?EndModalLoop@CWnd@@UAEXH@Z
	DD	FLAT:?OnCommand@CWnd@@MAEHIJ@Z
	DD	FLAT:?OnNotify@CWnd@@MAEHIJPAJ@Z
	DD	FLAT:?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ
	DD	FLAT:?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z
	DD	FLAT:?BeginModalState@CWnd@@UAEXXZ
	DD	FLAT:?EndModalState@CWnd@@UAEXXZ
	DD	FLAT:?PreTranslateMessage@CWnd@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z
	DD	FLAT:?WindowProc@CWnd@@MAEJIIJ@Z
	DD	FLAT:?OnWndMsg@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?DefWindowProcA@CWnd@@MAEJIIJ@Z
	DD	FLAT:?PostNcDestroy@CWnd@@MAEXXZ
	DD	FLAT:?OnChildNotify@CListCtrl@@MAEHIIJPAJ@Z
	DD	FLAT:?CheckAutoCenter@CWnd@@UAEHXZ
	DD	FLAT:?IsFrameWnd@CWnd@@UBEHXZ
	DD	FLAT:?SetOccDialogInfo@CWnd@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z
	DD	FLAT:?DrawItem@CListCtrl@@UAEXPAUtagDRAWITEMSTRUCT@@@Z
CONST	ENDS
;	COMDAT ??_7CEditConfig@@6B@
CONST	SEGMENT
??_7CEditConfig@@6B@ DD FLAT:?GetRuntimeClass@CDialog@@UBEPAUCRuntimeClass@@XZ ; CEditConfig::`vftable'
	DD	FLAT:??_ECEditConfig@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CObject@@UBEXXZ
	DD	FLAT:?Dump@CObject@@UBEXAAVCDumpContext@@@Z
	DD	FLAT:?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z
	DD	FLAT:?OnFinalRelease@CWnd@@UAEXXZ
	DD	FLAT:?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z
	DD	FLAT:?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z
	DD	FLAT:?GetTypeInfoCount@CCmdTarget@@UAEIXZ
	DD	FLAT:?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ
	DD	FLAT:?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z
	DD	FLAT:?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ
	DD	FLAT:?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ
	DD	FLAT:?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ
	DD	FLAT:?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ
	DD	FLAT:?GetInterfaceMap@CCmdTarget@@MBEPBUAFX_INTERFACEMAP@@XZ
	DD	FLAT:?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ
	DD	FLAT:?OnCreateAggregates@CCmdTarget@@UAEHXZ
	DD	FLAT:?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z
	DD	FLAT:?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z
	DD	FLAT:?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z
	DD	FLAT:?PreSubclassWindow@CWnd@@UAEXXZ
	DD	FLAT:?Create@CWnd@@UAEHPBD0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z
	DD	FLAT:?DestroyWindow@CWnd@@UAEHXZ
	DD	FLAT:?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTA@@@Z
	DD	FLAT:?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z
	DD	FLAT:?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOA@@@Z
	DD	FLAT:?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z
	DD	FLAT:?WinHelpA@CWnd@@UAEXKI@Z
	DD	FLAT:?ContinueModal@CWnd@@UAEHXZ
	DD	FLAT:?EndModalLoop@CWnd@@UAEXH@Z
	DD	FLAT:?OnCommand@CWnd@@MAEHIJ@Z
	DD	FLAT:?OnNotify@CWnd@@MAEHIJPAJ@Z
	DD	FLAT:?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ
	DD	FLAT:?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z
	DD	FLAT:?BeginModalState@CWnd@@UAEXXZ
	DD	FLAT:?EndModalState@CWnd@@UAEXXZ
	DD	FLAT:?PreTranslateMessage@CDialog@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z
	DD	FLAT:?WindowProc@CWnd@@MAEJIIJ@Z
	DD	FLAT:?OnWndMsg@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?DefWindowProcA@CWnd@@MAEJIIJ@Z
	DD	FLAT:?PostNcDestroy@CWnd@@MAEXXZ
	DD	FLAT:?OnChildNotify@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?CheckAutoCenter@CDialog@@UAEHXZ
	DD	FLAT:?IsFrameWnd@CWnd@@UBEHXZ
	DD	FLAT:?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z
	DD	FLAT:?DoModal@CDialog@@UAEHXZ
	DD	FLAT:?OnInitDialog@CEditConfig@@MAEHXZ
	DD	FLAT:?OnSetFont@CDialog@@UAEXPAVCFont@@@Z
	DD	FLAT:?OnOK@CDialog@@MAEXXZ
	DD	FLAT:?OnCancel@CDialog@@MAEXXZ
	DD	FLAT:?PreInitDialog@CDialog@@MAEXXZ
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T78796	DD	019930520H
	DD	03H
	DD	FLAT:$T78799
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78799	DD	0ffffffffH
	DD	FLAT:$L78785
	DD	00H
	DD	FLAT:$L78786
	DD	01H
	DD	FLAT:$L78787
xdata$x	ENDS
;	COMDAT ??0CEditConfig@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z
_TEXT	SEGMENT
_ptk$ = 8
_pParent$ = 12
_this$ = -16
__$EHRec$ = -12
??0CEditConfig@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z PROC NEAR ; CEditConfig::CEditConfig, COMDAT

; 24   : {

	push	-1
	push	$L78797
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	mov	eax, DWORD PTR _pParent$[esp+12]
	push	esi
	push	edi
	mov	esi, ecx
	push	eax
	push	203					; 000000cbH
	mov	DWORD PTR _this$[esp+32], esi
	call	??0CDialog@@QAE@IPAVCWnd@@@Z		; CDialog::CDialog
	lea	edi, DWORD PTR [esi+888]
	mov	DWORD PTR __$EHRec$[esp+32], 0
	mov	ecx, edi
	call	??0CWnd@@QAE@XZ				; CWnd::CWnd
	mov	DWORD PTR [edi], OFFSET FLAT:??_7CListCtrl@@6B@ ; CListCtrl::`vftable'
	lea	edi, DWORD PTR [esi+960]
	mov	BYTE PTR __$EHRec$[esp+32], 1
	mov	ecx, edi
	call	??0CString@@QAE@XZ			; CString::CString
	mov	ecx, DWORD PTR _ptk$[esp+20]

; 25   : 	//{{AFX_DATA_INIT(CEditConfig)
; 26   : 	m_TopLayer = 0;
; 27   : 	m_BottomLayer = 0;
; 28   : 	m_Triggers = _T("");

	push	OFFSET FLAT:??_C@_00A@?$AA@		; `string'
	mov	DWORD PTR [esi+964], ecx
	mov	ecx, edi
	mov	BYTE PTR __$EHRec$[esp+36], 2
	mov	DWORD PTR [esi], OFFSET FLAT:??_7CEditConfig@@6B@ ; CEditConfig::`vftable'
	mov	DWORD PTR [esi+952], 0
	mov	DWORD PTR [esi+956], 0
	call	??4CString@@QAEABV0@PBD@Z		; CString::operator=

; 29   : 	//}}AFX_DATA_INIT
; 30   : }

	mov	ecx, DWORD PTR __$EHRec$[esp+24]
	mov	eax, esi
	pop	edi
	pop	esi
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 16					; 00000010H
	ret	8
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78785:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
$L78786:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 888				; 00000378H
	jmp	??1CListCtrl@@UAE@XZ			; CListCtrl::~CListCtrl
$L78787:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 960				; 000003c0H
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78797:
	mov	eax, OFFSET FLAT:$T78796
	jmp	___CxxFrameHandler
text$x	ENDS
??0CEditConfig@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z ENDP ; CEditConfig::CEditConfig
EXTRN	??3@YAXPAX@Z:NEAR				; operator delete
;	COMDAT ??_GCListCtrl@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8
??_GCListCtrl@@UAEPAXI@Z PROC NEAR			; CListCtrl::`scalar deleting destructor', COMDAT
	push	esi
	mov	esi, ecx
	call	??1CListCtrl@@UAE@XZ			; CListCtrl::~CListCtrl
	test	BYTE PTR ___flags$[esp], 1
	je	SHORT $L78809
	push	esi
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
$L78809:
	mov	eax, esi
	pop	esi
	ret	4
??_GCListCtrl@@UAEPAXI@Z ENDP				; CListCtrl::`scalar deleting destructor'
_TEXT	ENDS
;	COMDAT ?Serialize@CObject@@UAEXAAVCArchive@@@Z
_TEXT	SEGMENT
?Serialize@CObject@@UAEXAAVCArchive@@@Z PROC NEAR	; CObject::Serialize, COMDAT

; 21   : 	{ /* CObject does not serialize anything by default */ }

	ret	4
?Serialize@CObject@@UAEXAAVCArchive@@@Z ENDP		; CObject::Serialize
_TEXT	ENDS
;	COMDAT ?AssertValid@CObject@@UBEXXZ
_TEXT	SEGMENT
?AssertValid@CObject@@UBEXXZ PROC NEAR			; CObject::AssertValid, COMDAT

; 37   : 	{ /* no asserts in release builds */ }

	ret	0
?AssertValid@CObject@@UBEXXZ ENDP			; CObject::AssertValid
_TEXT	ENDS
;	COMDAT ?Dump@CObject@@UBEXAAVCDumpContext@@@Z
_TEXT	SEGMENT
?Dump@CObject@@UBEXAAVCDumpContext@@@Z PROC NEAR	; CObject::Dump, COMDAT

; 39   : 	{ /* no dumping in release builds */ }

	ret	4
?Dump@CObject@@UBEXAAVCDumpContext@@@Z ENDP		; CObject::Dump
_TEXT	ENDS
PUBLIC	??1CEditConfig@@UAE@XZ				; CEditConfig::~CEditConfig
;	COMDAT ??_GCEditConfig@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8
??_GCEditConfig@@UAEPAXI@Z PROC NEAR			; CEditConfig::`scalar deleting destructor', COMDAT
	push	esi
	mov	esi, ecx
	call	??1CEditConfig@@UAE@XZ			; CEditConfig::~CEditConfig
	test	BYTE PTR ___flags$[esp], 1
	je	SHORT $L78821
	push	esi
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
$L78821:
	mov	eax, esi
	pop	esi
	ret	4
??_GCEditConfig@@UAEPAXI@Z ENDP				; CEditConfig::`scalar deleting destructor'
_TEXT	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T78828	DD	019930520H
	DD	02H
	DD	FLAT:$T78830
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78830	DD	0ffffffffH
	DD	FLAT:$L78824
	DD	00H
	DD	FLAT:$L78825
xdata$x	ENDS
;	COMDAT ??1CEditConfig@@UAE@XZ
_TEXT	SEGMENT
_this$ = -16
__$EHRec$ = -12
??1CEditConfig@@UAE@XZ PROC NEAR			; CEditConfig::~CEditConfig, COMDAT
	push	-1
	push	$L78829
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	push	esi
	mov	esi, ecx
	mov	DWORD PTR _this$[esp+20], esi
	lea	ecx, DWORD PTR [esi+960]
	mov	DWORD PTR __$EHRec$[esp+28], 1
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR [esi+888]
	mov	BYTE PTR __$EHRec$[esp+28], 0
	call	??1CListCtrl@@UAE@XZ			; CListCtrl::~CListCtrl
	mov	ecx, esi
	mov	DWORD PTR __$EHRec$[esp+28], -1
	call	??1CDialog@@UAE@XZ			; CDialog::~CDialog
	mov	ecx, DWORD PTR __$EHRec$[esp+20]
	pop	esi
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 16					; 00000010H
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78824:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
$L78825:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 888				; 00000378H
	jmp	??1CListCtrl@@UAE@XZ			; CListCtrl::~CListCtrl
$L78829:
	mov	eax, OFFSET FLAT:$T78828
	jmp	___CxxFrameHandler
text$x	ENDS
??1CEditConfig@@UAE@XZ ENDP				; CEditConfig::~CEditConfig
EXTRN	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z:NEAR ; DDX_Control
EXTRN	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z:NEAR ; DDV_MinMaxUInt
EXTRN	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z:NEAR ; DDV_MinMaxFloat
EXTRN	?DDV_MaxChars@@YGXPAVCDataExchange@@ABVCString@@H@Z:NEAR ; DDV_MaxChars
EXTRN	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z:NEAR	; DDX_Text
EXTRN	?DDX_Text@@YGXPAVCDataExchange@@HAAI@Z:NEAR	; DDX_Text
EXTRN	?DDX_Text@@YGXPAVCDataExchange@@HAAVCString@@@Z:NEAR ; DDX_Text
EXTRN	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z:NEAR	; DDX_Text
EXTRN	?DDX_Check@@YGXPAVCDataExchange@@HAAH@Z:NEAR	; DDX_Check
EXTRN	__fltused:NEAR
;	COMDAT ?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT
_pDX$ = 8
?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z PROC NEAR ; CEditConfig::DoDataExchange, COMDAT

; 34   : {

	push	ebx
	push	esi

; 35   : 	CDialog::DoDataExchange(pDX);
; 36   : 	//{{AFX_DATA_MAP(CEditConfig)
; 37   : 	DDX_Control(pDX, IDC_EC_TRIALLIST, m_TrialList);

	mov	esi, DWORD PTR _pDX$[esp+4]
	push	edi
	mov	edi, ecx
	lea	eax, DWORD PTR [edi+888]
	push	eax
	push	217					; 000000d9H
	push	esi
	call	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z ; DDX_Control

; 38   : 	DDX_Text(pDX, IDC_EC_TOPLAYER, m_TopLayer);

	lea	ebx, DWORD PTR [edi+952]
	push	ebx
	push	208					; 000000d0H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAI@Z	; DDX_Text

; 39   : 	DDV_MinMaxUInt(pDX, m_TopLayer, 0, 100);

	mov	ecx, DWORD PTR [ebx]
	push	100					; 00000064H
	push	0
	push	ecx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 40   : 	DDX_Text(pDX, IDC_EC_BOTTOMLAYER, m_BottomLayer);

	lea	ebx, DWORD PTR [edi+956]
	push	ebx
	push	209					; 000000d1H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAI@Z	; DDX_Text

; 41   : 	DDV_MinMaxUInt(pDX, m_BottomLayer, 0, 100);

	mov	edx, DWORD PTR [ebx]
	push	100					; 00000064H
	push	0
	push	edx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 42   : 	DDX_Text(pDX, IDC_EC_TRIGGERCOUNT, m_Triggers);

	lea	ebx, DWORD PTR [edi+960]
	push	ebx
	push	210					; 000000d2H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAVCString@@@Z ; DDX_Text

; 43   : 	DDV_MaxChars(pDX, m_Triggers, 63);

	push	63					; 0000003fH
	push	ebx
	push	esi
	call	?DDV_MaxChars@@YGXPAVCDataExchange@@ABVCString@@H@Z ; DDV_MaxChars

; 44   : 	//}}AFX_DATA_MAP
; 45   : 	DDX_Text(pDX, IDC_EC_CELLOVERFLOW, C.CellOverflow);

	lea	ebx, DWORD PTR [edi+104]
	push	ebx
	push	205					; 000000cdH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 46   : 	DDV_MinMaxUInt(pDX, C.CellOverflow, 32, 1024);

	mov	eax, DWORD PTR [ebx]
	push	1024					; 00000400H
	push	32					; 00000020H
	push	eax
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 47   : 	DDX_Text(pDX, IDC_EC_CELLSX, C.CellNumX);

	lea	ebx, DWORD PTR [edi+108]
	push	ebx
	push	203					; 000000cbH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 48   : 	DDV_MinMaxUInt(pDX, C.CellNumX, 1, 100);

	mov	ecx, DWORD PTR [ebx]
	push	100					; 00000064H
	push	1
	push	ecx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 49   : 	DDX_Text(pDX, IDC_EC_CELLSY, C.CellNumY);

	lea	ebx, DWORD PTR [edi+112]
	push	ebx
	push	204					; 000000ccH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 50   : 	DDV_MinMaxUInt(pDX, C.CellNumY, 1, 100);

	mov	edx, DWORD PTR [ebx]
	push	100					; 00000064H
	push	1
	push	edx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 51   : 	DDX_Text(pDX, IDC_EC_ALIGNTOL, C.AlignTol);

	lea	ebx, DWORD PTR [edi+124]
	push	ebx
	push	211					; 000000d3H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 52   : 	DDV_MinMaxFloat(pDX, C.AlignTol, 0.f, 10.f);

	push	1092616192				; 41200000H
	push	0
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 53   : 	DDX_Text(pDX, IDC_EC_MAXGRAINS, C.MaxGrains);

	lea	ebx, DWORD PTR [edi+96]
	push	ebx
	push	201					; 000000c9H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 54   : 	DDV_MinMaxUInt(pDX, C.MaxGrains, 1000, 500000);

	mov	eax, DWORD PTR [ebx]
	push	500000					; 0007a120H
	push	1000					; 000003e8H
	push	eax
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 55   : 	DDX_Text(pDX, IDC_EC_MAXLAYERS, C.LayerNum);

	lea	ebx, DWORD PTR [edi+100]
	push	ebx
	push	202					; 000000caH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 56   : 	DDV_MinMaxUInt(pDX, C.LayerNum, 10, 200);

	mov	ecx, DWORD PTR [ebx]
	push	200					; 000000c8H
	push	10					; 0000000aH
	push	ecx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 57   : 	DDX_Text(pDX, IDC_EC_MAXPIXELS, C.PixMax);

	lea	ebx, DWORD PTR [edi+120]
	push	ebx
	push	207					; 000000cfH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 58   : 	DDV_MinMaxUInt(pDX, C.PixMax, 1, 10000000);

	mov	edx, DWORD PTR [ebx]
	push	10000000				; 00989680H
	push	1
	push	edx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 59   : 	DDX_Text(pDX, IDC_EC_MAXSLOPE, C.MaxSlope);

	lea	ebx, DWORD PTR [edi+852]
	push	ebx
	push	214					; 000000d6H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 60   : 	DDV_MinMaxFloat(pDX, C.MaxSlope, 0.f, 2.f);

	push	1073741824				; 40000000H
	push	0
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 61   : 	DDX_Text(pDX, IDC_EC_MINPIXELS, C.PixMin);

	lea	ebx, DWORD PTR [edi+116]
	push	ebx
	push	206					; 000000ceH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 62   : 	DDV_MinMaxUInt(pDX, C.PixMin, 0, 10000000);

	mov	eax, DWORD PTR [ebx]
	push	10000000				; 00989680H
	push	0
	push	eax
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 63   : 	DDX_Text(pDX, IDC_EC_NPTMINV, C.NptMinV);

	lea	ebx, DWORD PTR [edi+836]
	push	ebx
	push	216					; 000000d8H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 64   : 	DDV_MinMaxFloat(pDX, C.NptMinV, 4, 50);

	push	1112014848				; 42480000H
	push	1082130432				; 40800000H
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 65   : 	DDX_Text(pDX, IDC_EC_NPTMINH, C.NptMinH);

	lea	ebx, DWORD PTR [edi+840]
	push	ebx
	push	220					; 000000dcH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 66   : 	DDV_MinMaxFloat(pDX, C.NptMinH, 4, 50);

	push	1112014848				; 42480000H
	push	1082130432				; 40800000H
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 67   : 	DDX_Text(pDX, IDC_EC_NPTMIN01, C.NptMin01);

	lea	ebx, DWORD PTR [edi+844]
	push	ebx
	push	221					; 000000ddH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 68   : 	DDV_MinMaxFloat(pDX, C.NptMin01, 4, 50);

	push	1112014848				; 42480000H
	push	1082130432				; 40800000H
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 69   : 	DDX_Text(pDX, IDC_EC_MINSLOPE, C.MinSlope);

	lea	ebx, DWORD PTR [edi+848]
	push	ebx
	push	213					; 000000d5H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 70   : 	DDV_MinMaxFloat(pDX, C.MinSlope, -1.e-003f, 2.f);

	push	1073741824				; 40000000H
	push	-1165815185				; ba83126fH
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 71   : 	DDX_Text(pDX, IDC_EC_PROCESSORS, C.Processors);

	lea	ebx, DWORD PTR [edi+856]
	push	ebx
	push	222					; 000000deH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 72   : 	DDV_MinMaxUInt(pDX, C.Processors, 1, MAX_PROCESSORS);

	mov	ecx, DWORD PTR [ebx]
	push	8
	push	1
	push	ecx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 73   : 	DDX_Text(pDX, IDC_EC_MAXTRACKINGTIME, C.MaxTrackingTime);

	lea	ebx, DWORD PTR [edi+860]
	push	ebx
	push	225					; 000000e1H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 74   : 	DDV_MinMaxUInt(pDX, C.MaxTrackingTime, 20, 1000);

	mov	edx, DWORD PTR [ebx]
	push	1000					; 000003e8H
	push	20					; 00000014H
	push	edx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 75   : 	DDX_Text(pDX, IDC_EC_REPLICARADIUS, C.ReplicaRadius);

	lea	ebx, DWORD PTR [edi+864]
	push	ebx
	push	212					; 000000d4H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 76   : 	DDV_MinMaxFloat(pDX, C.ReplicaRadius, 0.f, 5.f);

	push	1084227584				; 40a00000H
	push	0
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 77   : 	DDX_Text(pDX, IDC_EC_REPLICASAMPLEDIVIDER, C.ReplicaSampleDivider);

	lea	ebx, DWORD PTR [edi+868]
	push	ebx
	push	215					; 000000d7H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 78   : 	DDV_MinMaxUInt(pDX, C.ReplicaSampleDivider, 1, 64);

	mov	eax, DWORD PTR [ebx]
	push	64					; 00000040H
	push	1
	push	eax
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 79   : 	DDX_Text(pDX, IDC_EC_MINREPLICAS, C.MinReplicas);

	lea	ebx, DWORD PTR [edi+872]
	push	ebx
	push	223					; 000000dfH
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Text

; 80   : 	DDV_MinMaxUInt(pDX, C.MinReplicas, 8, 1000);

	mov	ecx, DWORD PTR [ebx]
	push	1000					; 000003e8H
	push	8
	push	ecx
	push	esi
	call	?DDV_MinMaxUInt@@YGXPAVCDataExchange@@III@Z ; DDV_MinMaxUInt

; 81   : 	DDX_Text(pDX, IDC_EC_MAXREPLICASPREAD, C.MaxReplicaSpread);

	lea	ebx, DWORD PTR [edi+876]
	push	ebx
	push	224					; 000000e0H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 82   : 	DDV_MinMaxFloat(pDX, C.MaxReplicaSpread, 0.01f, 3.f);

	push	1077936128				; 40400000H
	push	1008981770				; 3c23d70aH
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 83   : 	DDX_Text(pDX, IDC_EC_DISCARDSHADOWSIGMA, C.DiscardShadowSigma);

	lea	ebx, DWORD PTR [edi+880]
	push	ebx
	push	226					; 000000e2H
	push	esi
	call	?DDX_Text@@YGXPAVCDataExchange@@HAAM@Z	; DDX_Text

; 84   : 	DDV_MinMaxFloat(pDX, C.DiscardShadowSigma, 0.0f, 4.0f);

	push	1082130432				; 40800000H
	push	0
	push	ebx
	push	esi
	call	?DDV_MinMaxFloat@@YGXPAVCDataExchange@@ABMMM@Z ; DDV_MinMaxFloat

; 85   : 	DDX_Check(pDX, IDC_EC_CHECKGRAINSPACING, C.CheckGrainSpacing);

	add	edi, 884				; 00000374H
	push	edi
	push	227					; 000000e3H
	push	esi
	call	?DDX_Check@@YGXPAVCDataExchange@@HAAH@Z	; DDX_Check
	pop	edi
	pop	esi
	pop	ebx

; 86   : }

	ret	4
?DoDataExchange@CEditConfig@@MAEXPAVCDataExchange@@@Z ENDP ; CEditConfig::DoDataExchange
_TEXT	ENDS
EXTRN	__imp_?messageMap@CDialog@@1UAFX_MSGMAP@@B:QWORD
;	COMDAT ?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ PROC NEAR ; CEditConfig::_GetBaseMessageMap, COMDAT

; 89   : BEGIN_MESSAGE_MAP(CEditConfig, CDialog)

	mov	eax, DWORD PTR __imp_?messageMap@CDialog@@1UAFX_MSGMAP@@B
	ret	0
?_GetBaseMessageMap@CEditConfig@@KGPBUAFX_MSGMAP@@XZ ENDP ; CEditConfig::_GetBaseMessageMap
_TEXT	ENDS
;	COMDAT ?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ PROC NEAR ; CEditConfig::GetMessageMap, COMDAT

; 89   : BEGIN_MESSAGE_MAP(CEditConfig, CDialog)

	mov	eax, OFFSET FLAT:?messageMap@CEditConfig@@1UAFX_MSGMAP@@B ; CEditConfig::messageMap
	ret	0
?GetMessageMap@CEditConfig@@MBEPBUAFX_MSGMAP@@XZ ENDP	; CEditConfig::GetMessageMap
_TEXT	ENDS
PUBLIC	??_C@_0M@CACD@Trial?5Error?$AA@			; `string'
PUBLIC	??_C@_0BA@LLJB@Too?5many?5trials?$AA@		; `string'
PUBLIC	??_C@_0CL@NNLD@Bottom?5layer?5must?5be?5higher?5than@ ; `string'
PUBLIC	??_C@_01KMAE@?0?$AA@				; `string'
PUBLIC	??_C@_02MECO@?$CFd?$AA@				; `string'
PUBLIC	??_C@_0CK@IJH@Triggers?5must?5be?5comma?9separated@ ; `string'
EXTRN	?InsertItem@CListCtrl@@QAEHIHPBDIIHJ@Z:NEAR	; CListCtrl::InsertItem
EXTRN	??YCString@@QAEABV0@ABV0@@Z:NEAR		; CString::operator+=
EXTRN	??YCString@@QAEABV0@PBD@Z:NEAR			; CString::operator+=
EXTRN	?Format@CString@@QAAXPBDZZ:NEAR			; CString::Format
EXTRN	__imp__sprintf:NEAR
EXTRN	__imp__sscanf:NEAR
EXTRN	__imp__strtok:NEAR
EXTRN	?SetItemText@CListCtrl@@QAEHHHPBD@Z:NEAR	; CListCtrl::SetItemText
EXTRN	?MessageBoxA@CWnd@@QAEHPBD0I@Z:NEAR		; CWnd::MessageBoxA
EXTRN	?UpdateData@CWnd@@QAEHH@Z:NEAR			; CWnd::UpdateData
;	COMDAT ??_C@_0M@CACD@Trial?5Error?$AA@
; File D:\Program Files\Microsoft Visual Studio\VC98\MFC\INCLUDE\afx.inl
_DATA	SEGMENT
??_C@_0M@CACD@Trial?5Error?$AA@ DB 'Trial Error', 00H	; `string'
_DATA	ENDS
;	COMDAT ??_C@_0BA@LLJB@Too?5many?5trials?$AA@
_DATA	SEGMENT
??_C@_0BA@LLJB@Too?5many?5trials?$AA@ DB 'Too many trials', 00H ; `string'
_DATA	ENDS
;	COMDAT ??_C@_0CL@NNLD@Bottom?5layer?5must?5be?5higher?5than@
_DATA	SEGMENT
??_C@_0CL@NNLD@Bottom?5layer?5must?5be?5higher?5than@ DB 'Bottom layer mu'
	DB	'st be higher than Top layer', 00H		; `string'
_DATA	ENDS
;	COMDAT ??_C@_01KMAE@?0?$AA@
_DATA	SEGMENT
??_C@_01KMAE@?0?$AA@ DB ',', 00H			; `string'
_DATA	ENDS
;	COMDAT ??_C@_02MECO@?$CFd?$AA@
_DATA	SEGMENT
??_C@_02MECO@?$CFd?$AA@ DB '%d', 00H			; `string'
_DATA	ENDS
;	COMDAT ??_C@_0CK@IJH@Triggers?5must?5be?5comma?9separated@
_DATA	SEGMENT
??_C@_0CK@IJH@Triggers?5must?5be?5comma?9separated@ DB 'Triggers must be '
	DB	'comma-separated integers', 00H		; `string'
_DATA	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T78859	DD	019930520H
	DD	02H
	DD	FLAT:$T78867
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78867	DD	0ffffffffH
	DD	FLAT:$L78845
	DD	00H
	DD	FLAT:$L78846
xdata$x	ENDS
;	COMDAT ?OnAdd@CEditConfig@@IAEXXZ
_TEXT	SEGMENT
__$EHRec$ = -12
_tempstr$ = -268
_sub$ = -276
_tsub$ = -272
?OnAdd@CEditConfig@@IAEXXZ PROC NEAR			; CEditConfig::OnAdd, COMDAT

; 104  : {

	mov	eax, DWORD PTR fs:__except_list
	push	-1
	push	$L78865
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	sub	esp, 264				; 00000108H
	push	ebx
	push	ebp
	push	esi
	push	edi
	mov	ebp, ecx

; 105  : 	// TODO: Add your control notification handler code here
; 106  : 	UpdateData();

	push	1
	call	?UpdateData@CWnd@@QAEHH@Z		; CWnd::UpdateData

; 107  : 	if (C.TrialCount >= MAX_TRIALS)

	mov	eax, DWORD PTR [ebp+128]
	cmp	eax, 16					; 00000010H
	jl	SHORT $L78371

; 108  : 	{
; 109  : 		MessageBox("Too many trials", "Trial Error");

	push	0
	push	OFFSET FLAT:??_C@_0M@CACD@Trial?5Error?$AA@ ; `string'
	push	OFFSET FLAT:??_C@_0BA@LLJB@Too?5many?5trials?$AA@ ; `string'
	mov	ecx, ebp
	call	?MessageBoxA@CWnd@@QAEHPBD0I@Z		; CWnd::MessageBoxA

; 110  : 		return;

	jmp	$L78370
$L78371:

; 111  : 		};
; 112  : 	if (m_BottomLayer <= m_TopLayer)

	mov	ecx, DWORD PTR [ebp+952]
	mov	edx, DWORD PTR [ebp+956]
	cmp	edx, ecx
	ja	SHORT $L78374

; 113  : 	{
; 114  : 		MessageBox("Bottom layer must be higher than Top layer", "Trial Error");

	push	0
	push	OFFSET FLAT:??_C@_0M@CACD@Trial?5Error?$AA@ ; `string'
	push	OFFSET FLAT:??_C@_0CL@NNLD@Bottom?5layer?5must?5be?5higher?5than@ ; `string'
	mov	ecx, ebp
	call	?MessageBoxA@CWnd@@QAEHPBD0I@Z		; CWnd::MessageBoxA

; 115  : 		return;

	jmp	$L78370
$L78374:

; 116  : 		};
; 117  : 	C.Trials[C.TrialCount].TopLayer = m_TopLayer;

	lea	edx, DWORD PTR [eax+eax*4+15]
	lea	eax, DWORD PTR [eax+edx*2+3]
	mov	DWORD PTR [ebp+eax*4], ecx

; 118  : 	C.Trials[C.TrialCount].BottomLayer = m_BottomLayer;

	mov	eax, DWORD PTR [ebp+128]
	lea	ecx, DWORD PTR [eax+eax*4]
	lea	edx, DWORD PTR [eax+ecx*2]
	mov	eax, DWORD PTR [ebp+956]

; 119  : 	char tempstr[256];
; 120  : 	CString sub;

	lea	ecx, DWORD PTR _sub$[esp+292]
	mov	DWORD PTR [ebp+edx*4+136], eax
	call	??0CString@@QAE@XZ			; CString::CString

; 121  : 	CString tsub;

	lea	ecx, DWORD PTR _tsub$[esp+292]
	mov	DWORD PTR __$EHRec$[esp+300], 0
	call	??0CString@@QAE@XZ			; CString::CString

; 122  : 	strcpy(tempstr, m_Triggers);

	mov	edi, DWORD PTR [ebp+960]
	or	ecx, -1
	xor	eax, eax
	lea	edx, DWORD PTR _tempstr$[esp+292]
	repne scasb
	not	ecx
	sub	edi, ecx

; 123  : 	char *str = strtok(tempstr, ",");

	push	OFFSET FLAT:??_C@_01KMAE@?0?$AA@	; `string'
	mov	eax, ecx
	mov	esi, edi
	mov	edi, edx
	mov	BYTE PTR __$EHRec$[esp+304], 1
	shr	ecx, 2
	rep movsd
	mov	ecx, eax
	and	ecx, 3
	rep movsb
	mov	edi, DWORD PTR __imp__strtok
	lea	ecx, DWORD PTR _tempstr$[esp+296]
	push	ecx
	call	edi

; 124  : 	int i;
; 125  : 	for (i = 0; i < MAX_TRIGGERS && str; i++)

	mov	ebx, DWORD PTR __imp__sscanf
	add	esp, 8
	xor	esi, esi
$L78382:
	test	eax, eax
	je	$L78384

; 126  : 	{
; 127  : 		if (sscanf(str, "%d", &C.Trials[C.TrialCount].Triggers[i]) != 1)

	mov	ecx, DWORD PTR [ebp+128]
	lea	edx, DWORD PTR [ecx+ecx*4]
	add	ecx, esi
	lea	edx, DWORD PTR [ecx+edx*2]
	lea	ecx, DWORD PTR [ebp+edx*4+144]
	push	ecx
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	eax
	call	ebx
	add	esp, 12					; 0000000cH
	cmp	eax, 1
	jne	$L78862

; 133  : 			}
; 134  : 		tsub.Format("%d", C.Trials[C.TrialCount].Triggers[i]);

	mov	eax, DWORD PTR [ebp+128]
	lea	edx, DWORD PTR [eax+eax*4]
	add	eax, esi
	lea	ecx, DWORD PTR [eax+edx*2]
	lea	eax, DWORD PTR _tsub$[esp+292]
	mov	edx, DWORD PTR [ebp+ecx*4+144]
	push	edx
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	eax
	call	?Format@CString@@QAAXPBDZZ		; CString::Format
	add	esp, 12					; 0000000cH

; 135  : 		if (i > 0) sub += ",";

	test	esi, esi
	jle	SHORT $L78391
	push	OFFSET FLAT:??_C@_01KMAE@?0?$AA@	; `string'
	lea	ecx, DWORD PTR _sub$[esp+296]
	call	??YCString@@QAEABV0@PBD@Z		; CString::operator+=
$L78391:

; 136  : 		sub += tsub;

	lea	ecx, DWORD PTR _tsub$[esp+292]
	push	ecx
	lea	ecx, DWORD PTR _sub$[esp+296]
	call	??YCString@@QAEABV0@ABV0@@Z		; CString::operator+=

; 137  : 		str = strtok(0, ",");

	push	OFFSET FLAT:??_C@_01KMAE@?0?$AA@	; `string'
	push	0
	call	edi
	add	esp, 8
	inc	esi
	cmp	esi, 8
	jl	$L78382
$L78384:

; 138  : 		}
; 139  : 	C.Trials[C.TrialCount].TriggerCount = i;

	mov	eax, DWORD PTR [ebp+128]

; 140  : 	sprintf(tempstr, "%d", C.Trials[C.TrialCount].TopLayer);

	mov	edi, DWORD PTR __imp__sprintf
	lea	ecx, DWORD PTR [eax+eax*4]
	lea	edx, DWORD PTR [eax+ecx*2]
	mov	DWORD PTR [ebp+edx*4+140], esi
	mov	eax, DWORD PTR [ebp+128]
	add	eax, 3
	lea	ecx, DWORD PTR [eax+eax*4]
	lea	edx, DWORD PTR [eax+ecx*2]
	lea	ecx, DWORD PTR _tempstr$[esp+292]
	mov	eax, DWORD PTR [ebp+edx*4]
	push	eax
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	ecx
	call	edi

; 141  : 	m_TrialList.InsertItem(C.TrialCount, tempstr);

	mov	eax, DWORD PTR [ebp+128]
	add	esp, 12					; 0000000cH
	lea	edx, DWORD PTR _tempstr$[esp+292]
	lea	esi, DWORD PTR [ebp+888]
	push	0
	push	0
	push	0
	push	0
	push	edx
	push	eax
	push	1
	mov	ecx, esi
	call	?InsertItem@CListCtrl@@QAEHIHPBDIIHJ@Z	; CListCtrl::InsertItem

; 142  : 	sprintf(tempstr, "%d", C.Trials[C.TrialCount].BottomLayer);

	mov	eax, DWORD PTR [ebp+128]
	lea	ecx, DWORD PTR [eax+eax*4]
	lea	edx, DWORD PTR [eax+ecx*2]
	lea	ecx, DWORD PTR _tempstr$[esp+292]
	mov	eax, DWORD PTR [ebp+edx*4+136]
	push	eax
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	ecx
	call	edi

; 143  : 	m_TrialList.SetItemText(C.TrialCount, 1, tempstr);

	mov	eax, DWORD PTR [ebp+128]
	add	esp, 12					; 0000000cH
	lea	edx, DWORD PTR _tempstr$[esp+292]
	mov	ecx, esi
	push	edx
	push	1
	push	eax
	call	?SetItemText@CListCtrl@@QAEHHHPBD@Z	; CListCtrl::SetItemText

; 144  : 	m_TrialList.SetItemText(C.TrialCount, 2, sub);

	mov	ecx, DWORD PTR _sub$[esp+292]
	mov	edx, DWORD PTR [ebp+128]
	push	ecx
	push	2
	push	edx
	mov	ecx, esi
	call	?SetItemText@CListCtrl@@QAEHHHPBD@Z	; CListCtrl::SetItemText

; 145  : 	C.TrialCount++;

	inc	DWORD PTR [ebp+128]
$L78866:

; 146  : }

	lea	ecx, DWORD PTR _tsub$[esp+292]
	mov	BYTE PTR __$EHRec$[esp+300], 0
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR _sub$[esp+292]
	mov	DWORD PTR __$EHRec$[esp+300], -1
	call	??1CString@@QAE@XZ			; CString::~CString
$L78370:
	mov	ecx, DWORD PTR __$EHRec$[esp+292]
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 276				; 00000114H
	ret	0
$L78862:

; 128  : 		{
; 129  : 			MessageBox("Triggers must be comma-separated integers", "Trial Error");

	push	0
	push	OFFSET FLAT:??_C@_0M@CACD@Trial?5Error?$AA@ ; `string'
	push	OFFSET FLAT:??_C@_0CK@IJH@Triggers?5must?5be?5comma?9separated@ ; `string'
	mov	ecx, ebp
	call	?MessageBoxA@CWnd@@QAEHPBD0I@Z		; CWnd::MessageBoxA

; 130  : 			for (i = 0; i < MAX_TRIGGERS; i++)

	xor	ecx, ecx
$L78388:

; 131  : 				C.Trials[C.TrialCount].Triggers[i] = -1;

	mov	eax, DWORD PTR [ebp+128]
	lea	edx, DWORD PTR [eax+eax*4]
	add	eax, ecx
	inc	ecx
	lea	edx, DWORD PTR [eax+edx*2]
	cmp	ecx, 8
	mov	DWORD PTR [ebp+edx*4+144], -1
	jl	SHORT $L78388

; 132  : 			return;

	jmp	SHORT $L78866
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78845:
	lea	ecx, DWORD PTR _sub$[ebp]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78846:
	lea	ecx, DWORD PTR _tsub$[ebp]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78865:
	mov	eax, OFFSET FLAT:$T78859
	jmp	___CxxFrameHandler
text$x	ENDS
?OnAdd@CEditConfig@@IAEXXZ ENDP				; CEditConfig::OnAdd
EXTRN	__imp__SendMessageA@16:NEAR
;	COMDAT ?OnDel@CEditConfig@@IAEXXZ
_TEXT	SEGMENT
?OnDel@CEditConfig@@IAEXXZ PROC NEAR			; CEditConfig::OnDel, COMDAT

; 149  : {

	push	ebx
	mov	ebx, ecx
	push	ebp

; 150  : 	// TODO: Add your control notification handler code here
; 151  : 	int index = m_TrialList.GetSelectionMark();

	push	0
	mov	eax, DWORD PTR [ebx+920]
	push	0
	push	4162					; 00001042H
	push	eax
	call	DWORD PTR __imp__SendMessageA@16
	mov	ebp, eax

; 152  : 	if (index >= 0)

	test	ebp, ebp
	jl	SHORT $L78877

; 153  : 	{
; 154  : 		int i, j;
; 155  : 		for (i = index + 1; i < C.TrialCount + 1; i++)

	mov	ecx, DWORD PTR [ebx+128]
	lea	eax, DWORD PTR [ebp+1]
	inc	ecx
	push	edi
	cmp	eax, ecx
	jge	SHORT $L78401
	lea	edx, DWORD PTR [eax+eax*4+10]
	push	esi
	lea	ecx, DWORD PTR [eax+edx*2+2]
	lea	edx, DWORD PTR [ebx+ecx*4]
$L78399:

; 156  : 			C.Trials[i - 1] = C.Trials[i];

	lea	esi, DWORD PTR [edx+44]
	mov	ecx, 11					; 0000000bH
	mov	edi, edx
	inc	eax
	rep movsd
	mov	ecx, DWORD PTR [ebx+128]
	add	edx, 44					; 0000002cH
	inc	ecx
	cmp	eax, ecx
	jl	SHORT $L78399
	pop	esi
$L78401:

; 157  : 		for (j = 0; j < MAX_TRIGGERS; j++)

	lea	edx, DWORD PTR [eax+eax*4]

; 158  : 			C.Trials[i].Triggers[j] = -1;

	mov	ecx, 8

; 159  : 		C.TrialCount--;
; 160  : 		m_TrialList.DeleteItem(index);

	push	0
	push	ebp
	lea	eax, DWORD PTR [eax+edx*2]
	push	4104					; 00001008H
	lea	edi, DWORD PTR [ebx+eax*4+144]
	or	eax, -1
	rep stosd
	mov	edi, DWORD PTR [ebx+128]
	dec	edi
	mov	DWORD PTR [ebx+128], edi
	mov	ecx, DWORD PTR [ebx+920]
	push	ecx
	call	DWORD PTR __imp__SendMessageA@16
	pop	edi
$L78877:
	pop	ebp
	pop	ebx

; 161  : 		};
; 162  : }

	ret	0
?OnDel@CEditConfig@@IAEXXZ ENDP				; CEditConfig::OnDel
_TEXT	ENDS
PUBLIC	??_C@_03BJDM@Top?$AA@				; `string'
PUBLIC	??_C@_06LHCD@Bottom?$AA@			; `string'
PUBLIC	??_C@_07LCDE@Trigger?$AA@			; `string'
EXTRN	?InsertColumn@CListCtrl@@QAEHHPBDHHH@Z:NEAR	; CListCtrl::InsertColumn
EXTRN	?OnInitDialog@CDialog@@UAEHXZ:NEAR		; CDialog::OnInitDialog
;	COMDAT ??_C@_03BJDM@Top?$AA@
; File D:\Program Files\Microsoft Visual Studio\VC98\MFC\INCLUDE\afx.inl
_DATA	SEGMENT
??_C@_03BJDM@Top?$AA@ DB 'Top', 00H			; `string'
_DATA	ENDS
;	COMDAT ??_C@_06LHCD@Bottom?$AA@
_DATA	SEGMENT
??_C@_06LHCD@Bottom?$AA@ DB 'Bottom', 00H		; `string'
_DATA	ENDS
;	COMDAT ??_C@_07LCDE@Trigger?$AA@
_DATA	SEGMENT
??_C@_07LCDE@Trigger?$AA@ DB 'Trigger', 00H		; `string'
_DATA	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
$T78901	DD	019930520H
	DD	02H
	DD	FLAT:$T78909
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78909	DD	0ffffffffH
	DD	FLAT:$L78885
	DD	00H
	DD	FLAT:$L78886
xdata$x	ENDS
;	COMDAT ?OnInitDialog@CEditConfig@@MAEHXZ
_TEXT	SEGMENT
__$EHRec$ = -12
_this$ = -16
_str$ = -28
_temp$ = -20
?OnInitDialog@CEditConfig@@MAEHXZ PROC NEAR		; CEditConfig::OnInitDialog, COMDAT

; 165  : {

	push	-1
	push	$L78908
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	sub	esp, 16					; 00000010H
	push	ebx
	push	ebp
	push	esi
	mov	esi, ecx
	push	edi
	mov	DWORD PTR _this$[esp+44], esi

; 166  : 	CDialog::OnInitDialog();

	call	?OnInitDialog@CDialog@@UAEHXZ		; CDialog::OnInitDialog

; 167  : 	
; 168  : 	// TODO: Add extra initialization here
; 169  : 	m_TrialList.InsertColumn(0, "Top", LVCFMT_RIGHT, 60, 0);

	xor	ebp, ebp
	lea	ebx, DWORD PTR [esi+888]
	push	ebp
	push	60					; 0000003cH
	push	1
	push	OFFSET FLAT:??_C@_03BJDM@Top?$AA@	; `string'
	push	ebp
	mov	ecx, ebx
	call	?InsertColumn@CListCtrl@@QAEHHPBDHHH@Z	; CListCtrl::InsertColumn

; 170  : 	m_TrialList.InsertColumn(1, "Bottom", LVCFMT_RIGHT, 60, 1);

	push	1
	push	60					; 0000003cH
	push	1
	push	OFFSET FLAT:??_C@_06LHCD@Bottom?$AA@	; `string'
	push	1
	mov	ecx, ebx
	call	?InsertColumn@CListCtrl@@QAEHHPBDHHH@Z	; CListCtrl::InsertColumn

; 171  : 	m_TrialList.InsertColumn(2, "Trigger", LVCFMT_RIGHT, 80, 2);

	push	2
	push	80					; 00000050H
	push	1
	push	OFFSET FLAT:??_C@_07LCDE@Trigger?$AA@	; `string'
	push	2
	mov	ecx, ebx
	call	?InsertColumn@CListCtrl@@QAEHHPBDHHH@Z	; CListCtrl::InsertColumn

; 172  : 	ListView_SetExtendedListViewStyle(m_TrialList.m_hWnd, (LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES) | ListView_GetExtendedListViewStyle(m_TrialList.m_hWnd));

	mov	eax, DWORD PTR [esi+920]
	mov	edi, DWORD PTR __imp__SendMessageA@16
	push	ebp
	push	ebp
	push	4151					; 00001037H
	push	eax
	call	edi
	mov	ecx, DWORD PTR [esi+920]
	or	al, 33					; 00000021H
	push	eax
	push	ebp
	push	4150					; 00001036H
	push	ecx
	call	edi

; 173  : 	int i, j;
; 174  : 	CString str;

	lea	ecx, DWORD PTR _str$[esp+44]
	call	??0CString@@QAE@XZ			; CString::CString

; 175  : 	CString temp;

	lea	ecx, DWORD PTR _temp$[esp+44]
	mov	DWORD PTR __$EHRec$[esp+52], ebp
	call	??0CString@@QAE@XZ			; CString::CString

; 176  : 	for (i = 0; i < C.TrialCount; i++)

	mov	eax, DWORD PTR [esi+128]
	mov	BYTE PTR __$EHRec$[esp+52], 1
	test	eax, eax
	jle	$L78419

; 166  : 	CDialog::OnInitDialog();

	add	esi, 140				; 0000008cH
$L78417:

; 177  : 	{
; 178  : 		str.Format("%d", C.Trials[i].TopLayer);

	mov	edx, DWORD PTR [esi-8]
	lea	eax, DWORD PTR _str$[esp+44]
	push	edx
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	eax
	call	?Format@CString@@QAAXPBDZZ		; CString::Format

; 179  : 		m_TrialList.InsertItem(i, str);

	mov	ecx, DWORD PTR _str$[esp+56]
	add	esp, 12					; 0000000cH
	push	0
	push	0
	push	0
	push	0
	push	ecx
	push	ebp
	push	1
	mov	ecx, ebx
	call	?InsertItem@CListCtrl@@QAEHIHPBDIIHJ@Z	; CListCtrl::InsertItem

; 180  : 		str.Format("%d", C.Trials[i].BottomLayer);

	mov	edx, DWORD PTR [esi-4]
	lea	eax, DWORD PTR _str$[esp+44]
	push	edx
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	eax
	call	?Format@CString@@QAAXPBDZZ		; CString::Format

; 181  : 		m_TrialList.SetItemText(i, 1, str);

	mov	ecx, DWORD PTR _str$[esp+56]
	add	esp, 12					; 0000000cH
	push	ecx
	push	1
	push	ebp
	mov	ecx, ebx
	call	?SetItemText@CListCtrl@@QAEHHHPBD@Z	; CListCtrl::SetItemText

; 182  : 		str = "";

	push	OFFSET FLAT:??_C@_00A@?$AA@		; `string'
	lea	ecx, DWORD PTR _str$[esp+48]
	call	??4CString@@QAEABV0@PBD@Z		; CString::operator=

; 183  : 		for (j = 0; j < C.Trials[i].TriggerCount; j++)

	mov	eax, DWORD PTR [esi]
	xor	edi, edi
	test	eax, eax
	jle	SHORT $L78422
	lea	edx, DWORD PTR [esi+4]
	mov	DWORD PTR -24+[esp+44], edx
$L78420:

; 184  : 		{
; 185  : 			if (j > 0) str += ",";

	test	edi, edi
	jle	SHORT $L78423
	push	OFFSET FLAT:??_C@_01KMAE@?0?$AA@	; `string'
	lea	ecx, DWORD PTR _str$[esp+48]
	call	??YCString@@QAEABV0@PBD@Z		; CString::operator+=
$L78423:

; 186  : 			temp.Format("%d", C.Trials[i].Triggers[j]);

	mov	eax, DWORD PTR -24+[esp+44]
	lea	edx, DWORD PTR _temp$[esp+44]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	push	OFFSET FLAT:??_C@_02MECO@?$CFd?$AA@	; `string'
	push	edx
	call	?Format@CString@@QAAXPBDZZ		; CString::Format
	add	esp, 12					; 0000000cH

; 187  : 			str += temp;

	lea	eax, DWORD PTR _temp$[esp+44]
	lea	ecx, DWORD PTR _str$[esp+44]
	push	eax
	call	??YCString@@QAEABV0@ABV0@@Z		; CString::operator+=
	mov	ecx, DWORD PTR -24+[esp+44]
	mov	eax, DWORD PTR [esi]
	inc	edi
	add	ecx, 4
	cmp	edi, eax
	mov	DWORD PTR -24+[esp+44], ecx
	jl	SHORT $L78420
$L78422:

; 188  : 			}
; 189  : 		m_TrialList.SetItemText(i, 2, str);

	mov	ecx, DWORD PTR _str$[esp+44]
	push	ecx
	push	2
	push	ebp
	mov	ecx, ebx
	call	?SetItemText@CListCtrl@@QAEHHHPBD@Z	; CListCtrl::SetItemText
	mov	edx, DWORD PTR _this$[esp+44]
	inc	ebp
	add	esi, 44					; 0000002cH
	cmp	ebp, DWORD PTR [edx+128]
	jl	$L78417
$L78419:

; 190  : 		};
; 191  : 	return TRUE;  // return TRUE unless you set the focus to a control

	lea	ecx, DWORD PTR _temp$[esp+44]
	mov	BYTE PTR __$EHRec$[esp+52], 0
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR _str$[esp+44]
	mov	DWORD PTR __$EHRec$[esp+52], -1
	call	??1CString@@QAE@XZ			; CString::~CString

; 192  : 	              // EXCEPTION: OCX Property Pages should return FALSE
; 193  : }

	mov	ecx, DWORD PTR __$EHRec$[esp+44]
	pop	edi
	pop	esi
	pop	ebp
	mov	eax, 1
	pop	ebx
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 28					; 0000001cH
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78885:
	lea	ecx, DWORD PTR _str$[ebp]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78886:
	lea	ecx, DWORD PTR _temp$[ebp]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78908:
	mov	eax, OFFSET FLAT:$T78901
	jmp	___CxxFrameHandler
text$x	ENDS
?OnInitDialog@CEditConfig@@MAEHXZ ENDP			; CEditConfig::OnInitDialog
PUBLIC	??1CTestDlg@@UAE@XZ				; CTestDlg::~CTestDlg
EXTRN	?PutData@CSmartTrackerClass@@SAXPAUSySalConfig@@PAUConfigData@@@Z:NEAR ; CSmartTrackerClass::PutData
EXTRN	??0CTestDlg@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z:NEAR ; CTestDlg::CTestDlg
EXTRN	__imp__CoTaskMemFree@4:NEAR
;	COMDAT xdata$x
; File D:\SySal2\SmartTracker7\EditConfig.cpp
xdata$x	SEGMENT
$T78923	DD	019930520H
	DD	04H
	DD	FLAT:$T78925
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78925	DD	0ffffffffH
	DD	FLAT:$L78914
	DD	0ffffffffH
	DD	FLAT:$L78916
	DD	01H
	DD	FLAT:$L78917
	DD	02H
	DD	FLAT:$L78918
xdata$x	ENDS
;	COMDAT ?OnTest@CEditConfig@@IAEXXZ
_TEXT	SEGMENT
__$EHRec$ = -12
_OldC$ = -212
_NewC$ = -284
_Test$ = -140
?OnTest@CEditConfig@@IAEXXZ PROC NEAR			; CEditConfig::OnTest, COMDAT

; 196  : {

	push	-1
	push	$L78924
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	sub	esp, 272				; 00000110H
	push	ebx
	push	esi
	mov	esi, ecx

; 197  : 	// TODO: Add your control notification handler code here
; 198  : 	UpdateData();

	push	1
	call	?UpdateData@CWnd@@QAEHH@Z		; CWnd::UpdateData

; 199  : 
; 200  : 	SySalConfig OldC, NewC;
; 201  : 	OldC.Name[0] = NewC.Name[0] = 0;
; 202  : 	OldC.CountOfItems = NewC.CountOfItems = 0;
; 203  : 	OldC.pItems = NewC.pItems = 0;
; 204  : 
; 205  : 	pTk->GetConfig(&OldC);

	mov	eax, DWORD PTR [esi+964]
	xor	ebx, ebx
	add	eax, 4
	lea	edx, DWORD PTR _OldC$[esp+292]
	mov	BYTE PTR _NewC$[esp+292], bl
	mov	BYTE PTR _OldC$[esp+292], bl
	mov	DWORD PTR _NewC$[esp+356], ebx
	mov	DWORD PTR _OldC$[esp+356], ebx
	mov	DWORD PTR _NewC$[esp+360], ebx
	mov	DWORD PTR _OldC$[esp+360], ebx
	mov	ecx, DWORD PTR [eax]
	push	edx
	push	eax
	call	DWORD PTR [ecx+24]

; 206  : 
; 207  : 	CSmartTrackerClass::PutData(&NewC, &C);

	lea	eax, DWORD PTR [esi+96]
	lea	ecx, DWORD PTR _NewC$[esp+292]
	push	eax
	push	ecx
	call	?PutData@CSmartTrackerClass@@SAXPAUSySalConfig@@PAUConfigData@@@Z ; CSmartTrackerClass::PutData

; 208  : 
; 209  : 	pTk->SetConfig(&NewC);

	mov	eax, DWORD PTR [esi+964]
	add	esp, 8
	add	eax, 4
	lea	ecx, DWORD PTR _NewC$[esp+292]
	push	ecx
	push	eax
	mov	edx, DWORD PTR [eax]
	call	DWORD PTR [edx+20]

; 210  : 
; 211  : 	CTestDlg Test(pTk, this);

	mov	edx, DWORD PTR [esi+964]
	push	esi
	push	edx
	lea	ecx, DWORD PTR _Test$[esp+300]
	call	??0CTestDlg@@QAE@PAVCSmartTrackerClass@@PAVCWnd@@@Z ; CTestDlg::CTestDlg

; 212  : 	Test.DoModal();

	lea	ecx, DWORD PTR _Test$[esp+292]
	mov	DWORD PTR __$EHRec$[esp+300], ebx
	call	?DoModal@CDialog@@UAEHXZ		; CDialog::DoModal

; 213  : 
; 214  : 	pTk->SetConfig(&OldC);

	mov	esi, DWORD PTR [esi+964]
	lea	edx, DWORD PTR _OldC$[esp+292]
	push	edx
	mov	ecx, DWORD PTR [esi+4]
	lea	eax, DWORD PTR [esi+4]
	push	eax
	call	DWORD PTR [ecx+20]

; 215  : 
; 216  : 	if (OldC.pItems) CoTaskMemFree(OldC.pItems);

	mov	eax, DWORD PTR _OldC$[esp+360]
	mov	esi, DWORD PTR __imp__CoTaskMemFree@4
	cmp	eax, ebx
	je	SHORT $L78431
	push	eax
	call	esi
$L78431:

; 217  : 	if (NewC.pItems) CoTaskMemFree(NewC.pItems);

	mov	eax, DWORD PTR _NewC$[esp+360]
	cmp	eax, ebx
	je	SHORT $L78432
	push	eax
	call	esi
$L78432:

; 218  : }

	lea	ecx, DWORD PTR _Test$[esp+408]
	mov	DWORD PTR __$EHRec$[esp+300], 3
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR _Test$[esp+400]
	mov	BYTE PTR __$EHRec$[esp+300], 2
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR _Test$[esp+388]
	mov	BYTE PTR __$EHRec$[esp+300], 1
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR _Test$[esp+292]
	mov	DWORD PTR __$EHRec$[esp+300], -1
	call	??1CDialog@@UAE@XZ			; CDialog::~CDialog
	mov	ecx, DWORD PTR __$EHRec$[esp+292]
	pop	esi
	pop	ebx
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 284				; 0000011cH
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78914:
	lea	ecx, DWORD PTR _Test$[ebp]
	jmp	??1CTestDlg@@UAE@XZ			; CTestDlg::~CTestDlg
$L78916:
	lea	ecx, DWORD PTR _Test$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
$L78917:
	lea	ecx, DWORD PTR _Test$[ebp+96]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78918:
	lea	ecx, DWORD PTR _Test$[ebp+108]
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78924:
	mov	eax, OFFSET FLAT:$T78923
	jmp	___CxxFrameHandler
text$x	ENDS
?OnTest@CEditConfig@@IAEXXZ ENDP			; CEditConfig::OnTest
;	COMDAT xdata$x
xdata$x	SEGMENT
$T78935	DD	019930520H
	DD	03H
	DD	FLAT:$T78937
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	ORG $+4
$T78937	DD	0ffffffffH
	DD	FLAT:$L78930
	DD	00H
	DD	FLAT:$L78931
	DD	01H
	DD	FLAT:$L78932
xdata$x	ENDS
;	COMDAT ??1CTestDlg@@UAE@XZ
_TEXT	SEGMENT
__$EHRec$ = -12
_this$ = -16
??1CTestDlg@@UAE@XZ PROC NEAR				; CTestDlg::~CTestDlg, COMDAT
	push	-1
	push	$L78936
	mov	eax, DWORD PTR fs:__except_list
	push	eax
	mov	DWORD PTR fs:__except_list, esp
	push	ecx
	push	esi
	mov	esi, ecx
	mov	DWORD PTR _this$[esp+20], esi
	lea	ecx, DWORD PTR [esi+116]
	mov	DWORD PTR __$EHRec$[esp+28], 2
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR [esi+108]
	mov	BYTE PTR __$EHRec$[esp+28], 1
	call	??1CString@@QAE@XZ			; CString::~CString
	lea	ecx, DWORD PTR [esi+96]
	mov	BYTE PTR __$EHRec$[esp+28], 0
	call	??1CString@@QAE@XZ			; CString::~CString
	mov	ecx, esi
	mov	DWORD PTR __$EHRec$[esp+28], -1
	call	??1CDialog@@UAE@XZ			; CDialog::~CDialog
	mov	ecx, DWORD PTR __$EHRec$[esp+20]
	pop	esi
	mov	DWORD PTR fs:__except_list, ecx
	add	esp, 16					; 00000010H
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$L78930:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
$L78931:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 96					; 00000060H
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78932:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 108				; 0000006cH
	jmp	??1CString@@QAE@XZ			; CString::~CString
$L78936:
	mov	eax, OFFSET FLAT:$T78935
	jmp	___CxxFrameHandler
text$x	ENDS
??1CTestDlg@@UAE@XZ ENDP				; CTestDlg::~CTestDlg
PUBLIC	??_C@_0P@NFOI@HelpConfig?4htm?$AA@		; `string'
EXTRN	_HtmlHelpA@16:NEAR
EXTRN	?pHelpPath@CSmartTrackerClass@@2PADA:DWORD	; CSmartTrackerClass::pHelpPath
;	COMDAT ??_C@_0P@NFOI@HelpConfig?4htm?$AA@
; File D:\SySal2\SmartTracker7\EditConfig.cpp
_DATA	SEGMENT
??_C@_0P@NFOI@HelpConfig?4htm?$AA@ DB 'HelpConfig.htm', 00H ; `string'
_DATA	ENDS
;	COMDAT ?OnHelp@CEditConfig@@IAEXXZ
_TEXT	SEGMENT
?OnHelp@CEditConfig@@IAEXXZ PROC NEAR			; CEditConfig::OnHelp, COMDAT

; 222  : 	// TODO: Add your control notification handler code here
; 223  : 	HtmlHelp(this->m_hWnd, CSmartTrackerClass::pHelpPath, HH_DISPLAY_TOPIC, (DWORD)"HelpConfig.htm");	

	mov	eax, DWORD PTR ?pHelpPath@CSmartTrackerClass@@2PADA ; CSmartTrackerClass::pHelpPath
	mov	ecx, DWORD PTR [ecx+32]
	push	OFFSET FLAT:??_C@_0P@NFOI@HelpConfig?4htm?$AA@ ; `string'
	push	0
	push	eax
	push	ecx
	call	_HtmlHelpA@16

; 224  : }

	ret	0
?OnHelp@CEditConfig@@IAEXXZ ENDP			; CEditConfig::OnHelp
_TEXT	ENDS
;	COMDAT ?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT
?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z PROC NEAR ; CWnd::DoDataExchange, COMDAT

; 519  : 	{ } // default does nothing

	ret	4
?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z ENDP	; CWnd::DoDataExchange
_TEXT	ENDS
EXTRN	__imp__EnableWindow@8:NEAR
;	COMDAT ?BeginModalState@CWnd@@UAEXXZ
_TEXT	SEGMENT
?BeginModalState@CWnd@@UAEXXZ PROC NEAR			; CWnd::BeginModalState, COMDAT

; 523  : 	{ ::EnableWindow(m_hWnd, FALSE); }

	mov	eax, DWORD PTR [ecx+32]
	push	0
	push	eax
	call	DWORD PTR __imp__EnableWindow@8
	ret	0
?BeginModalState@CWnd@@UAEXXZ ENDP			; CWnd::BeginModalState
_TEXT	ENDS
;	COMDAT ?EndModalState@CWnd@@UAEXXZ
_TEXT	SEGMENT
?EndModalState@CWnd@@UAEXXZ PROC NEAR			; CWnd::EndModalState, COMDAT

; 525  : 	{ ::EnableWindow(m_hWnd, TRUE); }

	mov	eax, DWORD PTR [ecx+32]
	push	1
	push	eax
	call	DWORD PTR __imp__EnableWindow@8
	ret	0
?EndModalState@CWnd@@UAEXXZ ENDP			; CWnd::EndModalState
_TEXT	ENDS
END
